mutation removeTypeDempruntDemolitionFoyer($typesEmpruntsUUID: String!, $demolitionFoyerUUID: String!){
  removeTypeDempruntDemolitionFoyer(typesEmpruntsUUID: $typesEmpruntsUUID, demolitionFoyerUUID: $demolitionFoyerUUID)
}
