mutation saveDemolitionFoyer($demolitionFoyer: DemolitionFoyerInput!) {
  saveDemolitionFoyer(demolitionFoyer: $demolitionFoyer) {
    simulation{
      nom
    },
    id,
    numero,
    nomIntervention,
    nombreLogements,
    date,
    remboursementAnticipe,
    indexationIcc,
    prixRevient,
    fondsPropres,
    subventionsAnru,
    subventionsEtat,
    subventionsEpci,
    subventionsDepartement,
    subventionsRegion,
    subventionsCollecteur,
    autresSubventions,
    tauxEvolutionTfpb,
    tauxEvolutionMaintenance,
    tauxEvolutionGrosEntretien,
    totalEmprutns,
    typeEmpruntDemolitionFoyers{
      items{
        montant,
        datePremiere,
        typesEmprunts {
          id,
          nom
        }
      }
    }
  }
}
