mutation removeModeleDamortissement($modeleDamortissementUUID: String!, $simulationId: String!){
  removeModeleDamortissement(modeleDamortissementUUID: $modeleDamortissementUUID, simulationId: $simulationId)
}