mutation saveAccessionFraisStructure($fraiStructure: AccessionFraiStructureInput!) {
  saveAccessionFraisStructure(fraiStructure: $fraiStructure) {
    libelle,
    indexation,
    tauxDevolution,
    type,
    accessionFraisStructuresPeriodique{
      items{
        iteration,
        value
      }
    }
  }
}