mutation removeTypeDempruntTravauxFoyer($typesEmpruntsUUID: String!, $travauxFoyerUUID: String!) {
  removeTypeDempruntTravauxFoyer(
    typesEmpruntsUUID: $typesEmpruntsUUID,
    travauxFoyerUUID: $travauxFoyerUUID
  )
}
