mutation removeTypeDempruntTravauxImmobilise($typesEmpruntsUUID: String!, $travauxImmobiliseUUID: String!){
  removeTypeDempruntTravauxImmobilise(typesEmpruntsUUID: $typesEmpruntsUUID, travauxImmobiliseUUID: $travauxImmobiliseUUID)
}