mutation saveAutreCharge($autreCharge: AutreChargeInput!) {
  saveAutreCharge(autreCharge: $autreCharge) {
    numero,
    libelle,
    indexation,
    tauxDevolution,
    nature,
    autresChargesPeriodique{
      items{
        iteration,
        value
      }
    }
  }
}