query portageTresorerieParametre($simulationID: String!) {
    portageTresorerieParametre(simulationID: $simulationID){
    items {
      id,
      soldeEmplois,
      detteFournisseurs,
      promotionAccession,
      tauxInteretFinancement,
      tauxInteretConcours
    }
  }
}