mutation saveFraisStructure($fraiStructure: FraiStructureInput!) {
  saveFraisStructure(fraiStructure: $fraiStructure) {
    libelle,
    indexation,
    tauxDevolution,
    type,
    fraisStructuresPeriodique{
      items{
        iteration,
        value
      }
    }
  }
}