AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an Aurora instance (MySQL protocol)

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  VPCStackName:
    Description: The name of the parent networking stack in order to locate and reference resources created by that stack
    Type: String

  ECSClusterStackName:
    Description: The name of the parent AWS Fargate cluster stack in order to locate and reference resources created by that stack
    Type: String
  
  BastionStackName:
    Description: The name of the parent bastion stack in order to locate and reference resources created by that stack
    Type: String

  DatabaseUser:
    Description: Username of the database user
    Type: String
    Default: startupadmin
    MinLength: 5
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Name must begin with a letter and contain only alphanumeric characters

  DatabasePassword:
    Description: Password of the database user
    Type: String
    NoEcho: true
    MinLength: 6
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Password must contain only alphanumeric characters

  DatabaseName:
    Description: Name of the database
    Type: String
    Default: visialweb
    MinLength: 1
    MaxLength: 30
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Name must begin with a letter and contain only alphanumeric characters

  DBEngineVersion:
    Description: MySQL version
    Type: String
    Default: 5.7
    AllowedValues:
      - 5.6
      - 5.7

  EncryptionAtRest:
    Description: The optional flag for encryption at rest (db.t2.small and above)
    Type: String
    Default: false
    ConstraintDescription: Only true or false are allowed
    AllowedValues:
      - true
      - false

  DatabaseInstanceClass:
    Description: "Database instance class, e.g. db.t2.micro (free tier) - Engine support: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html"
    Default: db.t3.small
    Type: String
    ConstraintDescription: DB instance class not supported
    AllowedValues:
      - db.t2.xlarge
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.t3.xlarge
      - db.t3.2xlarge
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.12xlarge
      - db.r5.24xlarge

  # The database alarm configuration, currently not supported for Aurora PostgreSQL
  DatabaseAlarmMaxCpuPercent:
    Description: Database CPU % max for alarm
    Type: Number
    Default: 80
    MinValue: 1
    MaxValue: 99
    ConstraintDescription: Must be a percentage between 1-99%

  DatabaseAlarmReadLatencyMaxSeconds:
    Description: Read latency max for alarm
    Type: Number
    Default: 1
    MinValue: 1

  DatabaseAlarmWriteLatencyMaxSeconds:
    Description: Write latency max for alarm
    Type: Number
    Default: 1
    MinValue: 1

  DatabaseAlarmEvaluationPeriods:
    Description: The number of periods over which data is compared to the specified threshold
    Type: Number
    Default: 2
    MinValue: 2

  DatabaseAlarmEvaluationPeriodSeconds:
    Description: The time over which the specified statistic is applied. Specify time in seconds, in multiples of 60. Enhanced monitoring must be enabled if less than 500 seconds
    Type: Number
    Default: 300
    MinValue: 60
    ConstraintDescription: Must be at least 60 seconds

  EnhancedMonitoring:
    Description: The optional flag for enhanced monitoring (additional charges apply - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Monitoring.OS.html)
    Type: String
    Default: false
    ConstraintDescription: Only true or false are allowed
    AllowedValues:
      - true
      - false

  # Default is 200 MB
  DatabaseAlarmSwapUsageInBytes:
    Description: Number of swap usage bytes for alarm
    Default: 209715200
    Type: Number
    MinValue: 1
    ConstraintDescription: Enter a value of at least one byte

  EnableAlarms:
    Description: Set to true to enable (additional charges - https://aws.amazon.com/cloudwatch/pricing/)
    Type: String
    Default: false
    ConstraintDescription: Only true or false are allowed
    AllowedValues:
      - true
      - false

###############################################################################
# Conditions
############################################################################### 

Conditions:
  IsProd: !Equals [ !Ref EnvironmentName, production ]
  IsMySQL56: !Equals [ !Ref DBEngineVersion, '5.6']
  IsMySQL57: !Equals [ !Ref DBEngineVersion, '5.7']
  AlarmsEnabled: !Equals [ !Ref EnableAlarms, true ]
  EnhancedMonitoringEnabled: !Equals [ !Ref EnhancedMonitoring, true ]

###############################################################################
# Mappings
###############################################################################
 
Mappings:  
  DBFamilyMap: 
    "5.6": 
      family: "aurora5.6"
      engine: "aurora"
    "5.7":
      family: "aurora-mysql5.7"
      engine: "aurora-mysql"

Resources:
  EnhancedMonitoringRole:
    Type: AWS::IAM::Role
    Condition: EnhancedMonitoringEnabled
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

  DatabaseAlarmTopic:
    Type: AWS::SNS::Topic
    Condition: AlarmsEnabled
    Properties:
      DisplayName: Database Alarm Topic

  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Database subnet group
      SubnetIds:
        Fn::Split: 
          - ","
          - Fn::ImportValue: 
              !Sub "${VPCStackName}:PrivateSubnets" 
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName

  DBClusterParameterGroup56:
    Type: AWS::RDS::DBClusterParameterGroup
    Condition: IsMySQL56
    Properties:
      Description: "Aurora MySQL Cluster Parameter Group for  Cloudformation Stack - 5.6"
      Family: "aurora5.6"        
      Parameters:
        aurora_enable_zdr: 1
        server_audit_logging: 1
        server_audit_logs_upload: 1
        server_audit_events: 'CONNECT, QUERY, QUERY_DCL, QUERY_DDL, QUERY_DML, TABLE'
  
  DBClusterParameterGroup57:
    Type: AWS::RDS::DBClusterParameterGroup
    Condition: IsMySQL57
    Properties:
      Description: "Aurora MySQL Cluster Parameter Group for  Cloudformation Stack - 5.7"
      Family: "aurora-mysql5.7"
      Parameters:
        general_log: 1
        
  DBParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Join [ "- ", [ "Aurora MySQL Database Instance Parameter Group for Cloudformation Stack ", !Ref DatabaseName ] ]
      Family: !FindInMap [DBFamilyMap, !Ref DBEngineVersion, "family"] 

  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: !FindInMap [DBFamilyMap, !Ref DBEngineVersion, "engine"]
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      StorageEncrypted: !Ref EncryptionAtRest
      DatabaseName: !Ref DatabaseName
      DBClusterParameterGroupName: !If [IsMySQL56, !Ref DBClusterParameterGroup56, !Ref DBClusterParameterGroup57]
      Port: 3306
      VpcSecurityGroupIds:
        - !Ref AuroraDBSecurityGroup
    DependsOn: [DatabaseSubnetGroup, AuroraDBSecurityGroup]
  
  AuroraDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access database instance from application
      VpcId:
        Fn::ImportValue:
          !Join [':', [!Ref 'VPCStackName', 'VPC']]
  
  AuroraDBSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from application
      GroupId: !Ref 'AuroraDBSecurityGroup'
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId:
        Fn::ImportValue:
          !Join [':', [!Ref 'ECSClusterStackName', 'FargateContainerSecurityGroup']]

  AuroraDBSecurityGroupAllowBastionIngress:
    Type: AWS::EC2::SecurityGroupIngress    
    Properties:
      Description: Ingress from bastion security group
      GroupId: !Ref 'AuroraDBSecurityGroup'
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId:
        Fn::ImportValue:
          !Join [':', [!Ref 'BastionStackName', 'SecurityGroupId']]

  AuroraInstance0:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: !FindInMap [DBFamilyMap, !Ref DBEngineVersion, "engine"]
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: !Ref DatabaseInstanceClass
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      StorageEncrypted: !Ref EncryptionAtRest
      DBParameterGroupName: !Ref DBParamGroup
      MonitoringInterval: !If [ EnhancedMonitoringEnabled, 60, 0 ]
      MonitoringRoleArn: !If [ EnhancedMonitoringEnabled, !GetAtt EnhancedMonitoringRole.Arn, !Ref "AWS::NoValue" ]
      CopyTagsToSnapshot: true
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName
    DependsOn: AuroraCluster

  AuroraInstance1:
    Type: AWS::RDS::DBInstance
    Condition: IsProd
    Properties:
      Engine: !FindInMap [DBFamilyMap, !Ref DBEngineVersion, "engine"]
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: !Ref DatabaseInstanceClass
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      StorageEncrypted: !Ref EncryptionAtRest
      DBParameterGroupName: !Ref DBParamGroup
      MonitoringInterval: !If [ EnhancedMonitoringEnabled, 60, 0 ]
      MonitoringRoleArn: !If [ EnhancedMonitoringEnabled, !GetAtt EnhancedMonitoringRole.Arn, !Ref "AWS::NoValue" ]
      CopyTagsToSnapshot: true
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName
    DependsOn: AuroraCluster

  DatabaseCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmDescription: !Sub DB CPU utilization is over ${DatabaseAlarmMaxCpuPercent}% for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Unit: Percent
      Statistic: Average
      EvaluationPeriods: !Ref DatabaseAlarmEvaluationPeriods
      Period: !Ref DatabaseAlarmEvaluationPeriodSeconds
      Threshold: !Ref DatabaseAlarmMaxCpuPercent
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBClusterIdentifier
          Value: !Ref AuroraCluster
        - Name: Role
          Value: WRITER
      AlarmActions:
        - !Ref DatabaseAlarmTopic
    DependsOn: AuroraCluster

  DatabaseSelectLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmDescription: !Sub DB read latency is over ${DatabaseAlarmReadLatencyMaxSeconds} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: SelectLatency
      Unit: Seconds
      Statistic: Average
      EvaluationPeriods: !Ref DatabaseAlarmEvaluationPeriods
      Period: !Ref DatabaseAlarmEvaluationPeriodSeconds
      Threshold: !Ref DatabaseAlarmReadLatencyMaxSeconds
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBClusterIdentifier
          Value: !Ref AuroraCluster
        - Name: Role
          Value: WRITER
      AlarmActions:
        - !Ref DatabaseAlarmTopic
    DependsOn: AuroraCluster

  DatabaseInsertLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmDescription: !Sub DB insert latency is over ${DatabaseAlarmWriteLatencyMaxSeconds} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: InsertLatency
      Unit: Seconds
      Statistic: Average
      EvaluationPeriods: !Ref DatabaseAlarmEvaluationPeriods
      Period: !Ref DatabaseAlarmEvaluationPeriodSeconds
      Threshold: !Ref DatabaseAlarmWriteLatencyMaxSeconds
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBClusterIdentifier
          Value: !Ref AuroraCluster
        - Name: Role
          Value: WRITER
      AlarmActions:
        - !Ref DatabaseAlarmTopic
    DependsOn: AuroraCluster

  DatabaseUpdateLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmDescription: !Sub DB update latency is over ${DatabaseAlarmWriteLatencyMaxSeconds} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: UpdateLatency
      Unit: Seconds
      Statistic: Average
      EvaluationPeriods: !Ref DatabaseAlarmEvaluationPeriods
      Period: !Ref DatabaseAlarmEvaluationPeriodSeconds
      Threshold: !Ref DatabaseAlarmWriteLatencyMaxSeconds
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBClusterIdentifier
          Value: !Ref AuroraCluster
        - Name: Role
          Value: WRITER
      AlarmActions:
        - !Ref DatabaseAlarmTopic
    DependsOn: AuroraCluster

  DatabaseDeleteLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: AlarmsEnabled
    Properties:
      AlarmDescription: !Sub DB update latency is over ${DatabaseAlarmWriteLatencyMaxSeconds} for ${DatabaseAlarmEvaluationPeriods} period(s) of ${DatabaseAlarmEvaluationPeriodSeconds} seconds
      TreatMissingData: notBreaching
      Namespace: AWS/RDS
      MetricName: DeleteLatency
      Unit: Seconds
      Statistic: Average
      EvaluationPeriods: !Ref DatabaseAlarmEvaluationPeriods
      Period: !Ref DatabaseAlarmEvaluationPeriodSeconds
      Threshold: !Ref DatabaseAlarmWriteLatencyMaxSeconds
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DBClusterIdentifier
          Value: !Ref AuroraCluster
        - Name: Role
          Value: WRITER
      AlarmActions:
        - !Ref DatabaseAlarmTopic
    DependsOn: AuroraCluster

Outputs:
  Name:
    Description: Aurora Stack Name
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub ${AWS::StackName}:Name

  AuroraClusterId:
    Description: Aurora Cluster ID
    Value: !Ref AuroraCluster
    Export:
      Name: !Sub ${AWS::StackName}:AuroraClusterID

  AuroraDbURL:
    Description: Aurora Database URL
    Value: !GetAtt AuroraCluster.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}:DatabaseURL

  AuroraReadDbURL:
    Description: Aurora Database Read URL
    Value: !GetAtt AuroraCluster.ReadEndpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}:DatabaseReadURL

  DatabaseAlarmTopicArn:
    Description: Database Alarm Topic ARN
    Condition: AlarmsEnabled
    Value: !Ref DatabaseAlarmTopic
    Export:
      Name: !Sub ${AWS::StackName}:DatabaseAlarmTopicArn

  DatabaseAlarmTopicName:
    Description: Database Alarm Topic Name
    Condition: AlarmsEnabled
    Value: !GetAtt DatabaseAlarmTopic.TopicName
    Export:
      Name: !Sub ${AWS::StackName}:DatabaseAlarmTopicName
