mutation savePatrimoine($patrimoine: PatrimoineFoyerInput!) {
  savePatrimoineFoyer(patrimoineFoyer: $patrimoine) {
    simulation{
      nom
    },
    id,
    nGroupe,
    nSousGroupe,
    nomGroupe,
    informations,
    nombreLogements,
    secteurFinancier,
    natureOperation,
    tauxEvolutionRedevances,
  }
}
