mutation savePatrimoineFoyerParametre($simulationId: String!, $nombrePondereLogement: Int) {
  savePatrimoineFoyerParametre(simulationId:$simulationId, nombrePondereLogement:$nombrePondereLogement) {
    nombrePondereLogement
  }
}
