mutation saveFoyersFraisStructure($fraiStructure: FoyerFraiStructureInput!) {
  saveFoyersFraisStructure(fraiStructure: $fraiStructure) {
    libelle,
    indexation,
    tauxDevolution,
    type,
    foyersFraisStructuresPeriodique{
      items{
        iteration,
        value
      }
    }
  }
}