mutation saveResultatComptable($resultatComptable: ResultatComptableInput!) {
  saveResultatComptable(resultatComptable: $resultatComptable) {
    id,
    simulation{
      nom,
      description
    }
    libelle,
    resultatComptablePeriodique {
      items{
        iteration,
        value
      }
    }
  }
}