mutation saveCession($cession: CessionInput!){
  saveCession(cession: $cession) {
    id,
    simulation{
      nom
    },
    nGroupe,
    nSousGroupe,
    informations,
    nomGroupe,
    nature,
    indexerInflation,
    reductionTfpb,
    reductionGe,
 		reductionMaintenance,
    cessionFinMois,
    reductionAmortissementAnnuelle,
    reductionRepriseAnnuelle,
    dureeResiduelle,
    numero,
    nomCategory,
    loyerMensuel,
    nombreResiduelle,
    valeurComptable,
    type,
    cessionPeriodique{
      items{
        iteration,
        moisCession,
        nombreLogements,
        prixNetsCession,
        remboursementAnticipe,
        ecomoniesCapital,
        ecomoniesInterets,
        valeurCede
      }
    }
  }
}