query profilEvolutionLoyerParametre($simulationID: String!) {
    profilEvolutionLoyerParametre(simulationID: $simulationID) {
      items{
        id,
        plafonnementDesLoyersPratiquesAuLoyerPlafond
      }
  }
}