mutation saveProfilEvolutionLoyerParametre($idParametre: String!, $plafonnement: Boolean!){
    saveProfilEvolutionLoyerParametre(idParametre: $idParametre, plafonnement: $plafonnement){
    id
    }
}