mutation saveProfilEvolutionLoyer($profilEvolutionLoyer: ProfilEvolutionLoyerInput!) {
  saveProfilEvolutionLoyer(profilEvolutionLoyer: $profilEvolutionLoyer) {
    simulation{
      nom
    },
	id,
	numero,
    nom,
    appliquerIrl,
    profilsEvolutionLoyersPeriodique{
      items{
        s1,
        s2
      }
    }
  }
}
