mutation saveAccessionProduitCharge($produitCharge: AccessionProduitChargeInput!) {
  saveAccessionProduitCharge(produitCharge: $produitCharge) {
    libelle,
    indexation,
    tauxDevolution,
    type,
    accessionProduitsChargesPeriodique{
      items{
        iteration,
        value
      }
    }
  }
}