query fondDeRoulementParametre($simulationId: String!) {
  fondDeRoulementParametre(simulationId: $simulationId) {
    items{
      id,
      potentielFinancierTermination,
      fondsPropresSurOperation,
      depotDeGarantie
    }
  }
}
