mutation saveMaintenance($maintenance: MaintenanceInput!) {
  saveMaintenance(maintenance: $maintenance) {
    numero,
    nom,
    regie,
    tauxDevolution,
    indexation,
    type,
    nature,
    maintenancePeriodique{
      items{
        iteration,
        value
      }
    }
  }
}