<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractAccessionFraiStructurePeriodiqueDao;

/**
 * The AccessionFraiStructurePeriodiqueDao class will maintain the persistence of AccessionFraiStructurePeriodique class into the accession_frais_structures_periodique table.
 */
class AccessionFraiStructurePeriodiqueDao extends AbstractAccessionFraiStructurePeriodiqueDao
{
}
