<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractAccessionProduitChargeDao;
use App\Model\AccessionProduitCharge;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The AccessionProduitChargeDao class will maintain the persistence of AccessionProduitCharge class into the accession_produits_charges table.
 */
class AccessionProduitChargeDao extends AbstractAccessionProduitChargeDao
{
    /**
     * @return ResultIterator|AccessionProduitCharge[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }
}
