<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractAccessionCodificationDao;
use App\Model\AccessionCodification;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The AccessionCodificationDao class will maintain the persistence of AccessionCodification class into the accession_codifications table.
 */
class AccessionCodificationDao extends AbstractAccessionCodificationDao
{
    /**
     * @return ResultIterator|AccessionCodification[]
     */
    public function findBySimulationId(string $simulationId): ResultIterator
    {
        $filter = ['simulation_id' => $simulationId];

        return $this->find($filter);
    }
}
