<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractAccessionFraiStructureDao;
use App\Model\AccessionFraiStructure;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The AccessionFraiStructureDao class will maintain the persistence of AccessionFraiStructure class into the accession_frais_structures table.
 */
class AccessionFraiStructureDao extends AbstractAccessionFraiStructureDao
{
    /**
     * @return ResultIterator| AccessionFraiStructure[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }
}
