<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractAccessionProduitChargePeriodiqueDao;

/**
 * The AccessionProduitChargePeriodiqueDao class will maintain the persistence of AccessionProduitChargePeriodique class into the accession_produits_charges_periodique table.
 */
class AccessionProduitChargePeriodiqueDao extends AbstractAccessionProduitChargePeriodiqueDao
{
}
