<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractAnnuiteDao;
use App\Model\Annuite;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The AnnuiteDao class will maintain the persistence of Annuite class into the annuite table.
 */
class AnnuiteDao extends AbstractAnnuiteDao
{
    /**
     * @return ResultIterator|Annuite[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Annuite[]
     */
    public function findBySimulationIDAndType(string $simulationID, int $type): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'type' => $type,
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Annuite[]
     */
    public function findBySimulationAndLibelle(string $simulationID, string $libelle): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'libelle' => $libelle,
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Annuite[]
     */
    public function findBySimulationAndLibelleType(string $simulationID, string $libelle, int $type): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'libelle' => $libelle,
            'type' => 0,
        ];

        return $this->find($filter);
    }
}
