<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractAnnuitePeriodiqueDao;
use App\Model\AnnuitePeriodique;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\TDBMException;
use function Safe\sprintf;

/**
 * The AnnuitePeriodiqueDao class will maintain the persistence of AnnuitePeriodique class into the annuite_periodique table.
 */
class AnnuitePeriodiqueDao extends AbstractAnnuitePeriodiqueDao
{
    /**
     * @throws TDBMException
     * @throws StringsException
     */
    public function findOneByAnnuiteIDAndIterartion(string $annuiteID, int $iteration): AnnuitePeriodique
    {
        $annuitePeriodique= $this->findOne([
            'annuite_id' => $annuiteID,
            'iteration' => $iteration,
        ]);
        if ($annuitePeriodique === null) {
            throw new TDBMException(sprintf('No row found for annuite_id = %s and iteration = %d', $annuiteID, $iteration));
        }

        return $annuitePeriodique;
    }
}
