<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractAutreChargeDao;
use App\Model\AutreCharge;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The AutreChargeDao class will maintain the persistence of AutreCharge class into the autres_charges table.
 */
class AutreChargeDao extends AbstractAutreChargeDao
{
    /**
     * @return ResultIterator|AutreCharge[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|AutreCharge[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }

    public function calculateNumero(string $simulationID): int
    {
        $autreCharge = $this->findBySimulationID($simulationID);

        $count = $autreCharge->count();

        return $count + 1;
    }
}
