<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractAutreChargePeriodiqueDao;

/**
 * The AutreChargePeriodiqueDao class will maintain the persistence of AutreChargePeriodique class into the autres_charges_periodique table.
 */
class AutreChargePeriodiqueDao extends AbstractAutreChargePeriodiqueDao
{
}
