<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCcmiDao;
use App\Model\Ccmi;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The CcmiDao class will maintain the persistence of Ccmi class into the ccmi table.
 */
class CcmiDao extends AbstractCcmiDao
{
    /**
     * @return ResultIterator|Ccmi[]
     */
    public function findBySimulationId(string $simulationId): ResultIterator
    {
        return $this->find('simulation_id = :simulationId', ['simulation' => $simulationId]);
    }
}
