<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCcmiPeriodiqueDao;

/**
 * The CcmiPeriodiqueDao class will maintain the persistence of CcmiPeriodique class into the ccmi_periodique table.
 */
class CcmiPeriodiqueDao extends AbstractCcmiPeriodiqueDao
{
}
