<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCessionDao;
use App\Model\Cession;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The CessionDao class will maintain the persistence of Cession class into the cession table.
 */
class CessionDao extends AbstractCessionDao
{
    /**
     * @return ResultIterator|Cession[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Cession[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        $filter = ['simulation_id' => $simulationID];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Cession[]
     */
    public function findBySimulationIDAndType(string $simulationID, int $type): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'type' => $type,
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Cession[]
     */
    public function findOneByNGroupe(string $simulation, int $nGroupe, int $type): ResultIterator
    {
        return $this->find([
            'simulation_id' => $simulation,
            'n_groupe' => $nGroupe,
            'type' => $type,
        ]);
    }

    /**
     * Calculate the numero
     */
    public function calculateNumero(string $simulationID, int $type): int
    {
        $operations = $this->findBySimulationIDAndType($simulationID, $type);

        $count = $operations->count();

        return $count + 1;
    }
}
