<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCessionFoyerPeriodiqueDao;

/**
 * The CessionFoyerPeriodiqueDao class will maintain the persistence of CessionFoyerPeriodique class into the cessions_foyers_periodique table.
 */
class CessionFoyerPeriodiqueDao extends AbstractCessionFoyerPeriodiqueDao
{
}
