<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCessionFoyerDao;
use App\Model\CessionFoyer;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The CessionFoyerDao class will maintain the persistence of CessionFoyer class into the cessions_foyers table.
 */
class CessionFoyerDao extends AbstractCessionFoyerDao
{
    /**
     * @return ResultIterator|CessionFoyer[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        $filter = ['simulation_id' => $simulationID];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|CessionFoyer[]
     */
    public function findOneByNGroupe(string $simulation, int $nGroupe): ResultIterator
    {
        return $this->find([
            'simulation_id' => $simulation,
            'n_groupe' => $nGroupe,
        ]);
    }
}
