<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCessionPeriodiqueDao;

/**
 * The CessionPeriodiqueDao class will maintain the persistence of CessionPeriodique class into the cession_periodique table.
 */
class CessionPeriodiqueDao extends AbstractCessionPeriodiqueDao
{
}
