<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCgllAncolPeriodiqueDao;
use App\Model\CgllAncolPeriodique;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\TDBMException;
use function Safe\sprintf;

/**
 * The CgllAncolPeriodiqueDao class will maintain the persistence of CgllAncolPeriodique class into the cglls_ancols_periodique table.
 */
class CgllAncolPeriodiqueDao extends AbstractCgllAncolPeriodiqueDao
{
    /**
     * @throws TDBMException
     * @throws StringsException
     */
    public function findOneByCgllsAncolsIDAndIteration(string $cgllsAncolsID, int $iteration): CgllAncolPeriodique
    {
        $cgllsAncolsPeriodique = $this->findOne([
            'cglls_ancols_id' => $cgllsAncolsID,
            'iteration' => $iteration,
        ]);
        if ($cgllsAncolsPeriodique === null) {
            throw new TDBMException(sprintf('No row found for cglls_ancols_id = %s and iteration = %d', $cgllsAncolsID, $iteration));
        }

        return $cgllsAncolsPeriodique;
    }
}
