<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCgllAncolParametreDao;
use App\Model\CgllAncolParametre;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\TDBMException;
use function Safe\sprintf;

/**
 * The CgllAncolParametreDao class will maintain the persistence of CgllAncolParametre class into the cglls_ancols_parametre table.
 */
class CgllAncolParametreDao extends AbstractCgllAncolParametreDao
{
    /**
     * @throws TDBMException
     * @throws StringsException
     */
    public function findOneBySimulation(string $simulationId): CgllAncolParametre
    {
        $cgllsAncolsParametre = $this->findOne(['simulation_id' => $simulationId]);

        if ($cgllsAncolsParametre === null) {
            throw new TDBMException(sprintf('No row found for simulation_id = %s', $simulationId));
        }

        return $cgllsAncolsParametre;
    }
}
