<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCgllAncolDao;
use App\Model\CgllAncol;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The CgllAncolDao class will maintain the persistence of CgllAncol class into the cglls_ancols table.
 */
class CgllAncolDao extends AbstractCgllAncolDao
{
    /**
     * @return ResultIterator|CgllAncol[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }
}
