<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCodificationDao;
use App\Model\Codification;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The CodificationDao class will maintain the persistence of Codification class into the codifications table.
 */
class CodificationDao extends AbstractCodificationDao
{
    /**
     * @return ResultIterator|Codification[]
     */
    public function findBySimulationId(string $simulationId): ResultIterator
    {
        $filter = ['simulation_id' => $simulationId];

        return $this->find($filter);
    }

    public function getMaxNumeroBySimulationId(string $simulationId): int
    {
        $result = $this->find(['simulation_id' => $simulationId], [], 'numero DESC');

        $numero = 1;

        if ($result->count() > 0) {
            $numero = $result[0]->getNumero() + 1;
        }

        return $numero;
    }
}
