<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractDemolitionFoyerDao;
use App\Model\DemolitionFoyer;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The DemolitionFoyerDao class will maintain the persistence of DemolitionFoyer class into the demolition_foyers table.
 */
class DemolitionFoyerDao extends AbstractDemolitionFoyerDao
{
    /**
     * @return ResultIterator|DemolitionFoyer[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|DemolitionFoyer[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        $filter = ['simulation_id' => $simulationID];

        return $this->find($filter);
    }
}
