<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractDemolitionFoyerPeriodiqueDao;

/**
 * The DemolitionFoyerPeriodiqueDao class will maintain the persistence of DemolitionFoyerPeriodique class into the demolition_foyers_periodique table.
 */
class DemolitionFoyerPeriodiqueDao extends AbstractDemolitionFoyerPeriodiqueDao
{
}
