<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractDemolitionDao;
use App\Model\Demolition;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;
use function Safe\sprintf;

/**
 * The DemolitionDao class will maintain the persistence of Demolition class into the demolition table.
 */
class DemolitionDao extends AbstractDemolitionDao
{
    /**
     * @return ResultIterator|Demolition[]
     */
    public function findOneByNGroupe(string $simulation, int $nGroupe, int $type): ResultIterator
    {
        return $this->find([
            'simulation_id' => $simulation,
            'n_groupe' => $nGroupe,
            'type' => $type,
        ]);
    }

    /**
     * @return ResultIterator|Demolition[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter, [], sprintf('%s %s', 'n_groupe', 'ASC'));
    }

    /**
     * @return ResultIterator|Demolition[]
     */
    public function findBySimulationIDAndType(string $simulationID, int $type): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'type' => $type,
        ];

        return $this->find($filter, [], sprintf('%s %s', 'n_groupe', 'ASC'));
    }

    /**
     * @return ResultIterator|Demolition[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        $filter = ['simulation_id' => $simulationID];

        return $this->find($filter);
    }
}
