<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractDemolitionPeriodiqueDao;

/**
 * The DemolitionPeriodiqueDao class will maintain the persistence of DemolitionPeriodique class into the demolition_periodique table.
 */
class DemolitionPeriodiqueDao extends AbstractDemolitionPeriodiqueDao
{
}
