<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractDroitDao;
use App\Model\Droit;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\ResultIterator;
use function Safe\sprintf;

/**
 * The DroitDao class will maintain the persistence of Droit class into the droits table.
 */
class DroitDao extends AbstractDroitDao
{
    /**
     * @return Droit[]|ResultIterator
     *
     * @throws StringsException
     */
    public function findByFilters(?string $nom, ?string $libelle, ?string $categorie, ?string $sortColumn, ?string $sortOrder): ResultIterator
    {
        $sortColumn = $sortColumn ?? 'nom';
        $sortOrder = $sortOrder ?? 'ASC';

        return $this->find(
            'nom LIKE :nom AND libelle LIKE :libelle AND categorie LIKE :categorie',
            [
                'nom' => $nom ? sprintf('%%%s%%', $nom) : null,
                'description' => $libelle ? sprintf('%%%s%%', $libelle) : null,
                'categorie' => $categorie ? sprintf('%%%s%%', $categorie) : null,
            ],
            sprintf('%s %s', $sortColumn, $sortOrder)
        );
    }
}
