<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractEnsembleDao;
use App\Model\Ensemble;
use App\Model\Utilisateur;
use Safe\Exceptions\PcreException;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\ResultIterator;
use function count;
use function Safe\preg_replace;
use function Safe\sprintf;
use function strtolower;

/**
 * The EnsembleDao class will maintain the persistence of Ensemble class into the ensembles table.
 */
class EnsembleDao extends AbstractEnsembleDao
{
    /**
     * @return Ensemble[]|ResultIterator
     *
     * @throws StringsException
     * @throws PcreException
     */
    public function findByFilters(
        ?string $nom,
        ?string $description,
        ?string $creePar,
        ?string $modifiePar,
        ?string $entite,
        ?string $referent,
        bool $estAdministrateurCentral,
        string $sortColumn,
        string $sortOrder
    ): ResultIterator {
        // We need to specify this in order to prevent ambiguous error type because 'nom' is a field of multiple tables bellow
        if ($sortColumn === 'nom' || $sortColumn === 'description' || $sortColumn === 'dateCreation' || $sortColumn === 'dateModification') {
            // Changing camel case name into snake case so that column names matches with table column names
            $sortColumn  = strtolower(preg_replace(['/([a-z\d])([A-Z])/', '/([^_])([A-Z][a-z])/'], '$1_$2', $sortColumn));

            $sortColumn = 'ensembles.' . $sortColumn;
        }

        return $this->findFromSql(
            'ensembles
            LEFT JOIN utilisateurs as creePar ON creePar.id = ensembles.cree_par 
            LEFT JOIN utilisateurs as modifiePar ON modifiePar.id = ensembles.modifie_par
            
            LEFT JOIN ensembles_entites ON ensembles_entites.ensemble_id = ensembles.id
            LEFT JOIN entites ON ensembles_entites.entite_id = entites.id
            
            LEFT JOIN referents_ensembles ON referents_ensembles.ensemble_id = ensembles.id
            LEFT JOIN entites as referents ON referents.id = referents_ensembles.entite_id',
            'ensembles.nom LIKE :nom
            AND ensembles.description LIKE :description
            AND (creePar.nom LIKE :creePar OR creePar.prenom LIKE :creePar OR creePar.email LIKE :creePar)'
            . ($modifiePar ? ' AND (modifiePar.nom LIKE :modifiePar OR modifiePar.prenom LIKE :modifiePar OR modifiePar.email LIKE :modifiePar) ' : '')
            . ($entite ? ' AND entites.nom LIKE :entite ' : '')
            . ($referent ? ' AND referents.nom LIKE :referent ' : '')
            . ' AND (ensembles.est_active = true OR ensembles.est_active = :estAdministrateurCentral)',
            [
                'nom' => $nom ? sprintf('%%%s%%', $nom) : null,
                'description' => $description ? sprintf('%%%s%%', $description) : null,
                'creePar' => $creePar ? sprintf('%%%s%%', $creePar) : null,
                'modifiePar' => $modifiePar ? sprintf('%%%s%%', $modifiePar) : null,
                'entite' => $entite ? sprintf('%%%s%%', $entite) : null,
                'referent' => $referent ? sprintf('%%%s%%', $referent) : null,
                'estAdministrateurCentral' => ! $estAdministrateurCentral,
            ],
            sprintf('%s %s', $sortColumn, $sortOrder)
        );
    }

    public function isReferentEnsemble(Utilisateur $authenticatedUtilisateur, string $ensembleID): bool
    {
        if ($authenticatedUtilisateur->getEstAdministrateurCentral()) {
            return true;
        }
        $result = $this->findFromSql(
            'ensembles
            INNER JOIN referents_ensembles ON referents_ensembles.ensemble_id = ensembles.id
            INNER JOIN referents_entites ON referents_entites.entite_id = referents_ensembles.entite_id
            INNER JOIN utilisateurs ON utilisateurs.id = referents_entites.utilisateur_id',
            'utilisateurs.id = :authenticatedUtilisateur AND referents_ensembles.ensemble_id = :ensembleID',
            [
                'authenticatedUtilisateur' => $authenticatedUtilisateur->getId(),
                'ensembleID' => $ensembleID,
            ]
        );

        return count($result) > 0;
    }
}
