<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractEntiteDao;
use App\Model\Entite;
use App\Model\Utilisateur;
use Safe\Exceptions\PcreException;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\ResultIterator;
use TheCodingMachine\TDBM\TDBMException;
use function count;
use function Safe\preg_replace;
use function Safe\sprintf;
use function strtolower;

/**
 * The EntiteDao class will maintain the persistence of Entite class into the entites table.
 *
 * @method _getRelationships(string $string)
 */
class EntiteDao extends AbstractEntiteDao
{
    /**
     * Get all Entite records (exept admin)
     *
     * @return Entite[]|ResultIterator
     *
     * @throws StringsException
     */
    public function getAll(): ResultIterator
    {
        $sortColumn = 'nom';
        $sortOrder = 'ASC';
        $filter = 'code <> "ADMIN"';

        return $this->find($filter, [], sprintf('%s %s', $sortColumn, $sortOrder));
    }

    /**
     * @return Entite[]|ResultIterator
     *
     * @throws StringsException
     * @throws PcreException
     */
    public function findByFilters(
        ?string $nom,
        ?string $siren,
        ?string $code,
        ?string $type,
        ?string $codeOrganisme,
        ?string $typeOrganisme,
        ?string $creePar,
        ?string $modifiePar,
        ?string $utilisateur,
        ?string $referent,
        ?string $ensemble,
        bool $estAdministrateurCentral,
        string $sortColumn,
        string $sortOrder
    ): ResultIterator {
        // We need to specify this in order to prevent ambiguous error type because 'nom' is a field of multiple tables bellow
        if ($sortColumn === 'nom' || $sortColumn === 'typeOrganisme' || $sortColumn === 'codeOrganisme' || $sortColumn === 'dateCreation' || $sortColumn === 'dateModification') {
            // Changing camel case name into snake case so that column names matches with table column names
            $sortColumn  = strtolower(preg_replace(['/([a-z\d])([A-Z])/', '/([^_])([A-Z][a-z])/'], '$1_$2', $sortColumn));

            $sortColumn = 'entites.' . $sortColumn;
        }

        return $this->findFromSql(
            'entites
            LEFT JOIN utilisateurs as createur ON createur.id = entites.cree_par
            LEFT JOIN utilisateurs as modificateur ON modificateur.id = entites.modifie_par
            
            LEFT JOIN ensembles_entites ON ensembles_entites.entite_id = entites.id
            LEFT JOIN ensembles ON ensembles_entites.ensemble_id = ensembles.id
            
            LEFT JOIN referents_entites ON referents_entites.entite_id = entites.id
            LEFT JOIN utilisateurs as referents ON referents.id = referents_entites.utilisateur_id
            
            LEFT JOIN utilisateurs_roles_entites ON utilisateurs_roles_entites.entite_id = entites.id
            LEFT JOIN utilisateurs ON utilisateurs.id = utilisateurs_roles_entites.utilisateur_id',
            'entites.nom LIKE :nom
            AND siren LIKE :siren
            AND code LIKE :code
            AND code <> :hiddenCode
            AND type LIKE :type
            AND code_organisme LIKE :codeOrganisme
            AND type_organisme LIKE :typeOrganisme
            AND (createur.nom LIKE :creePar OR createur.prenom LIKE :creePar OR createur.email LIKE :creePar)'
            . ($modifiePar ? ' AND (modificateur.nom LIKE :modifiePar OR modificateur.prenom LIKE :modifiePar OR modificateur.email LIKE :modifiePar)' : '')
            . ($utilisateur ? ' AND (utilisateurs.nom LIKE :utilisateur OR utilisateurs.prenom LIKE :utilisateur OR utilisateurs.email LIKE :utilisateur)' : '')
            . ($referent ? ' AND (referents.nom LIKE :referent OR AND referents.prenom LIKE :referent OR AND referents.email LIKE :referent)' : '')
            . ($ensemble ? ' AND ensembles.nom LIKE :ensemble' : '')
            . ' AND (entites.est_activee = true OR entites.est_activee = :estAdministrateurCentral)',
            [
                'nom' => $nom ? sprintf('%%%s%%', $nom) : null,
                'siren' => $siren ? sprintf('%%%s%%', $siren) : null,
                'code' => $code ? sprintf('%%%s%%', $code): null,
                'type' => $type ? sprintf('%%%s%%', $type) : null,
                'codeOrganisme' => $codeOrganisme ? sprintf('%%%s%%', $codeOrganisme) : null,
                'typeOrganisme' => $typeOrganisme ? sprintf('%%%s%%', $typeOrganisme) : null,
                'creePar' => $creePar ? sprintf('%%%s%%', $creePar) : null,
                'modifiePar' => $modifiePar ? sprintf('%%%s%%', $modifiePar) : null,
                'utilisateur' => $utilisateur ? sprintf('%%%s%%', $utilisateur) : null,
                'referent' => $referent ? sprintf('%%%s%%', $referent) : null,
                'ensemble' => $ensemble ? sprintf('%%%s%%', $ensemble) : null,
                'hiddenCode' => 'ADMIN',
                'estAdministrateurCentral' => ! $estAdministrateurCentral,
            ],
            sprintf('%s %s', $sortColumn, $sortOrder)
        );
    }

    /**
     * @param string[] $entitesID
     *
     * @return Entite[]
     *
     * @throws TDBMException
     */
    public function getEntitesByIds(array $entitesID): array
    {
        $entites = [];
        foreach ($entitesID as $ID) {
            $entites[] = $this->getById($ID);
        }

        return $entites;
    }

    public function isReferentEntite(Utilisateur $authenticatedUtilisateur, string $entiteID): bool
    {
        if ($authenticatedUtilisateur->getEstAdministrateurCentral()) {
            return true;
        }
        $result = $this->findFromSql(
            'entites
            INNER JOIN referents_entites ON referents_entites.entite_id = entites.id
            INNER JOIN utilisateurs ON utilisateurs.id = referents_entites.utilisateur_id',
            'utilisateurs.id = :authenticatedUtilisateur AND referents_entites.entite_id = :entiteID',
            [
                'authenticatedUtilisateur' => $authenticatedUtilisateur->getId(),
                'entiteID' => $entiteID,
            ]
        );

        return count($result) > 0;
    }

    /**
     * @return Entite[]|ResultIterator
     */
    public function getEntitiesInEmsembleByReferentEntite(Utilisateur $authenticatedUtilisateur, string $ensembleID): ResultIterator
    {
        return $result = $this->findFromSql(
            'entites
            INNER JOIN ensembles_entites ON ensembles_entites.entite_id = entites.id
            INNER JOIN referents_entites ON referents_entites.entite_id = entites.id
            INNER JOIN utilisateurs ON utilisateurs.id = referents_entites.utilisateur_id',
            'utilisateurs.id = :authenticatedUtilisateur AND ensembles_entites.ensemble_id = :ensembleID',
            [
                'authenticatedUtilisateur' => $authenticatedUtilisateur->getId(),
                'ensembleID' => $ensembleID,
            ]
        );
    }
}
