<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractFondDeRoulementDao;
use App\Model\FondDeRoulement;
use TheCodingMachine\TDBM\ResultIterator;
use function Safe\sprintf;

/**
 * The FondDeRoulementDao class will maintain the persistence of FondDeRoulement class into the fond_de_roulement table.
 */
class FondDeRoulementDao extends AbstractFondDeRoulementDao
{
    /**
     * @return ResultIterator|FondDeRoulement[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID], [], sprintf('%s %s', 'deletable', 'ASC'));
    }

    /**
     * @return ResultIterator|FondDeRoulement[]
     */
    public function findBySimulationAndType(string $simulationID, string $type): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID, 'type' => $type], [], sprintf('%s %s', 'deletable', 'ASC'));
    }

    /**
     * @return ResultIterator|FondDeRoulement[]
     */
    public function findByNomAndType(string $nom, string $type): ResultIterator
    {
        return $this->find(['nom' => $nom, 'type' => $type]);
    }
}
