<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractFondDeRoulementPeriodiqueDao;

/**
 * The FondDeRoulementPeriodiqueDao class will maintain the persistence of FondDeRoulementPeriodique class into the fond_de_roulement_periodique table.
 */
class FondDeRoulementPeriodiqueDao extends AbstractFondDeRoulementPeriodiqueDao
{
}
