<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractFondDeRoulementParametreDao;
use App\Model\FondDeRoulementParametre;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The FondDeRoulementParametreDao class will maintain the persistence of FondDeRoulementParametre class into the fond_de_roulement_parametre table.
 */
class FondDeRoulementParametreDao extends AbstractFondDeRoulementParametreDao
{
    /**
     * @return ResultIterator|FondDeRoulementParametre[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        $filter = ['simulation_id' => $simulationID];

        return $this->find($filter);
    }
}
