<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractFoyerFraiStructurePeriodiqueDao;

/**
 * The FoyerFraiStructurePeriodiqueDao class will maintain the persistence of FoyerFraiStructurePeriodique class into the foyers_frais_structures_periodique table.
 */
class FoyerFraiStructurePeriodiqueDao extends AbstractFoyerFraiStructurePeriodiqueDao
{
}
