<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractFoyerFraiStructureDao;
use App\Model\FoyerFraiStructure;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The FoyerFraiStructureDao class will maintain the persistence of FoyerFraiStructure class into the foyers_frais_structures table.
 */
class FoyerFraiStructureDao extends AbstractFoyerFraiStructureDao
{
    /**
     * @return ResultIterator| FoyerFraiStructure[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }
}
