<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractFraiStructurePeriodiqueDao;

/**
 * The FraiStructurePeriodiqueDao class will maintain the persistence of FraiStructurePeriodique class into the frais_structures_periodique table.
 */
class FraiStructurePeriodiqueDao extends AbstractFraiStructurePeriodiqueDao
{
}
