<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractFraiStructureDao;
use App\Model\FraiStructure;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The FraiStructureDao class will maintain the persistence of FraiStructure class into the frais_structures table.
 */
class FraiStructureDao extends AbstractFraiStructureDao
{
     /**
      * @return ResultIterator| FraiStructure[]
      */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }
}
