<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractHypotheseDao;
use App\Model\Hypothese;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The HypotheseDao class will maintain the persistence of Hypothese class into the hypotheses table.
 */
class HypotheseDao extends AbstractHypotheseDao
{
    /**
     * @return ResultIterator|Hypothese[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }
}
