<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractIndiceTauxPeriodiqueDao;
use App\Model\IndiceTauxPeriodique;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\TDBMException;
use function Safe\sprintf;

/**
 * The IndiceTauxPeriodiqueDao class will maintain the persistence of IndiceTauxPeriodique class into the indices_taux_periodique table.
 */
class IndiceTauxPeriodiqueDao extends AbstractIndiceTauxPeriodiqueDao
{
    /**
     * @throws StringsException
     * @throws TDBMException
     */
    public function findOneByIndiceTauxIDAndIteration(string $indiceTauxID, int $iteration): IndiceTauxPeriodique
    {
        $indiceTauxPeriodique = $this->findOne([
            'indice_taux_id' => $indiceTauxID,
            'iteration' => $iteration,
        ]);
        if ($indiceTauxPeriodique === null) {
            throw new TDBMException(sprintf('No row found for indice_taux_id = %s and iteration = %s', $indiceTauxID, $iteration));
        }

        return $indiceTauxPeriodique;
    }
}
