<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractIndiceTauxDao;
use App\Model\IndiceTaux;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The IndiceTauxDao class will maintain the persistence of IndiceTaux class into the indices_taux table.
 */
class IndiceTauxDao extends AbstractIndiceTauxDao
{
    /**
     * @return ResultIterator|IndiceTaux[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }
}
