<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractInvitationEnsembleDao;
use App\Model\InvitationEnsemble;
use App\Model\Utilisateur;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The InvitationEnsembleDao class will maintain the persistence of InvitationEnsemble class into the invitations_ensembles table.
 */
class InvitationEnsembleDao extends AbstractInvitationEnsembleDao
{
    /**
     * @param null $orderBy
     * @param string[] $additionalTablesFetch
     *
     * @return InvitationEnsemble[]|ResultIterator
     */
    public function findByEnsemble(
        string $ensembleId,
        $orderBy = null,
        array $additionalTablesFetch = []
    ) {
        $filter = ['ensemble_id' => $ensembleId];

        return $this->find($filter, [], $orderBy, $additionalTablesFetch);
    }

    /**
     * @return InvitationEnsemble[]|ResultIterator
     */
    public function findByUtilisateur(Utilisateur $authenticatedUtilisateur)
    {
        return $this->findFromSql(
            'invitations_ensembles
            INNER JOIN referents_entites ON referents_entites.entite_id = invitations_ensembles.entite_id
            INNER JOIN utilisateurs ON utilisateurs.id = referents_entites.utilisateur_id',
            'utilisateurs.id = :authenticatedUtilisateur AND invitations_ensembles.statut = :statut',
            [
                'authenticatedUtilisateur' => $authenticatedUtilisateur->getId(),
                'statut' => 'En attente',
            ]
        );
    }

    /**
     * @return InvitationEnsemble[]|ResultIterator
     */
    public function findLeaveEnsemblesByUtilisateur(Utilisateur $authenticatedUtilisateur)
    {
        return $this->findFromSql(
            'invitations_ensembles
            INNER JOIN referents_ensembles ON referents_ensembles.ensemble_id = invitations_ensembles.ensemble_id
            INNER JOIN referents_entites ON referents_entites.entite_id = referents_ensembles.entite_id
            INNER JOIN utilisateurs ON utilisateurs.id = referents_entites.utilisateur_id',
            'utilisateurs.id = :authenticatedUtilisateur AND invitations_ensembles.statut = :statut',
            [
                'authenticatedUtilisateur' => $authenticatedUtilisateur->getId(),
                'statut' => 'Laisser',
            ]
        );
    }

    /**
     * @param string[] $additionalTablesFetch
     */
    public function findOneByEnsembleAndEntite(
        string $ensembleId,
        string $entiteId,
        array $additionalTablesFetch = []
    ): ?InvitationEnsemble {
        $filter = [
            'ensemble_id' => $ensembleId,
            'entite_id' => $entiteId,
        ];

        return $this->findOne($filter, [], $additionalTablesFetch);
    }
}
