<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractInvitationEntiteDao;
use App\Model\InvitationEntite;
use App\Model\Utilisateur;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The InvitationEntiteDao class will maintain the persistence of InvitationEntite class into the invitations_entites table.
 */
class InvitationEntiteDao extends AbstractInvitationEntiteDao
{
    /**
     * @param null $orderBy
     * @param string[] $additionalTablesFetch
     *
     * @return InvitationEntite[]|ResultIterator
     */
    public function findByEntite(
        string $entiteID,
        $orderBy = null,
        array $additionalTablesFetch = []
    ) {
        $filter = ['entite_id' => $entiteID];

        return $this->find($filter, [], $orderBy, $additionalTablesFetch);
    }

    /**
     * @param string[] $additionalTablesFetch
     */
    public function findOneByEntiteAndUtilisateur(
        string $entiteId,
        string $utilisateurId,
        array $additionalTablesFetch = []
    ): ?InvitationEntite {
        $filter = [
            'entite_id' => $entiteId,
            'utilisateur_id' => $utilisateurId,
        ];

        return $this->findOne($filter, [], $additionalTablesFetch);
    }

    /**
     * @return InvitationEntite[]|ResultIterator
     */
    public function findByUtilisateur(Utilisateur $authenticatedUtilisateur)
    {
        return $this->findFromSql(
            'invitations_entites
            INNER JOIN utilisateurs ON utilisateurs.id = invitations_entites.utilisateur_id',
            'utilisateurs.id = :authenticatedUtilisateur AND invitations_entites.statut = :statut',
            [
                'authenticatedUtilisateur' => $authenticatedUtilisateur->getId(),
                'statut' => 'En attente',
            ]
        );
    }
}
