<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractLotissementPeriodiqueDao;

/**
 * The LotissementPeriodiqueDao class will maintain the persistence of LotissementPeriodique class into the lotissement_periodique table.
 */
class LotissementPeriodiqueDao extends AbstractLotissementPeriodiqueDao
{
}
