<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractLotissementDao;
use App\Model\Lotissement;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The LotissementDao class will maintain the persistence of Lotissement class into the lotissement table.
 */
class LotissementDao extends AbstractLotissementDao
{
    /**
     * @return ResultIterator|Lotissement[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator| Lotissement[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }

    /**
     * @return ResultIterator|Lotissement[]
     */
    public function findBySimulationIDAndType(string $simulationID, int $type): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'type' => $type,
        ];

        return $this->find($filter);
    }
}
