<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractLoyerDao;
use App\Model\Loyer;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;
use function Safe\sprintf;

/**
 * The LoyerDao class will maintain the persistence of Loyer class into the loyer table.
 */
class LoyerDao extends AbstractLoyerDao
{
    /**
     * @return ResultIterator|Loyer[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Loyer[]
     */
    public function findBySimulationIDAndType(string $simulationID, int $type): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'type' => $type,
        ];

        return $this->find($filter, [], sprintf('%s %s', 'deletable', 'ASC'));
    }

    /**
     * @return ResultIterator|Loyer[]
     */
    public function findByNomAndType(string $nom, int $type): ResultIterator
    {
        $filter = [
            'nom' => $nom,
            'type' => $type,
            'deletable' => 0,
        ];

        return $this->find($filter);
    }
}
