<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractLoyerPeriodiqueDao;

/**
 * The LoyerPeriodiqueDao class will maintain the persistence of LoyerPeriodique class into the loyer_periodique table.
 */
class LoyerPeriodiqueDao extends AbstractLoyerPeriodiqueDao
{
}
