<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractMaintenanceDao;
use App\Model\Maintenance;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The MaintenanceDao class will maintain the persistence of Maintenance class into the maintenance table.
 */
class MaintenanceDao extends AbstractMaintenanceDao
{
    /**
     * Get a Maintenance filtered by simulationId.
     *
     * @return ResultIterator|Maintenance[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Maintenance[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }

    public function calculateNumero(string $simulationID): int
    {
        $maintenances = $this->findBySimulationID($simulationID);

        $count = $maintenances->count();

        return $count + 1;
    }
}
