<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractMaintenancePeriodiqueDao;

/**
 * The MaintenancePeriodiqueDao class will maintain the persistence of MaintenancePeriodique class into the maintenance_periodique table.
 */
class MaintenancePeriodiqueDao extends AbstractMaintenancePeriodiqueDao
{
}
