<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractMigrationVersionDao;

/**
 * The MigrationVersionDao class will maintain the persistence of MigrationVersion class into the migration_versions table.
 */
class MigrationVersionDao extends AbstractMigrationVersionDao
{
}
