<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractModeleDamortissementDao;
use App\Model\ModeleDamortissement;
use TheCodingMachine\TDBM\ResultIterator;
use function Safe\sprintf;

/**
 * The ModeleDamortissementDao class will maintain the persistence of ModeleDamortissement class into the modele_damortissement table.
 */
class ModeleDamortissementDao extends AbstractModeleDamortissementDao
{
    /**
     * @return ResultIterator|ModeleDamortissement[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        $sortColumn = 'numero';
        $sortOrder = 'ASC';

        return $this->find(['simulation_id' => $simulationID], [], sprintf('%s %s', $sortColumn, $sortOrder));
    }

    /**
     * @return ResultIterator|ModeleDamortissement[]
     */
    public function fetchBySimulationNom(string $simulationID, string $nom): ResultIterator
    {
        $sortColumn = 'numero';
        $sortOrder = 'ASC';

        return $this->find(['simulation_id' => $simulationID, 'nom' => $nom], [], sprintf('%s %s', $sortColumn, $sortOrder));
    }
}
