<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractNotificationDao;
use App\Model\Notification;
use App\Model\Utilisateur;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The NotificationDao class will maintain the persistence of Notification class into the notifications table.
 */
class NotificationDao extends AbstractNotificationDao
{
    /**
     * @return ResultIterator|Notification[]
     */
    public function findByUtilisateur(Utilisateur $utilisateur): ResultIterator
    {
        return $this->find(['utilisateur_id' => $utilisateur->getId(), 'statut' => 'unread']);
    }
}
