<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractNouveauxFoyerDao;
use App\Model\NouveauxFoyer;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The NouveauxFoyerDao class will maintain the persistence of NouveauxFoyer class into the nouveaux_foyer table.
 */
class NouveauxFoyerDao extends AbstractNouveauxFoyerDao
{
    /**
     * @return ResultIterator|NouveauxFoyer[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }
}
