<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractNouveauxFoyerPeriodiqueDao;

/**
 * The NouveauxFoyerPeriodiqueDao class will maintain the persistence of NouveauxFoyerPeriodique class into the nouveaux_foyer_periodique table.
 */
class NouveauxFoyerPeriodiqueDao extends AbstractNouveauxFoyerPeriodiqueDao
{
}
