<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractOperationDao;
use App\Model\Operation;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The OperationDao class will maintain the persistence of Operation class into the operation table.
 */
class OperationDao extends AbstractOperationDao
{
    /**
     * @return ResultIterator|Operation[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Operation[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        $filter = ['simulation_id' => $simulationID];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Operation[]
     */
    public function findBySimulationIDAndType(string $simulationID, int $type): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'type' => $type,
        ];

        return $this->find($filter);
    }

    public function calculateNoperation(string $simulationID, int $type): int
    {
        $operations = $this->findBySimulationIDAndType($simulationID, $type);

        $count = $operations->count();

        return $count + 1;
    }
}
