<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractOperationPeriodiqueDao;

/**
 * The OperationPeriodiqueDao class will maintain the persistence of OperationPeriodique class into the operation_periodique table.
 */
class OperationPeriodiqueDao extends AbstractOperationPeriodiqueDao
{
}
