<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPartagerDao;
use App\Model\Partager;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\ResultIterator;
use function Safe\sprintf;

/**
 * The PartagerDao class will maintain the persistence of Partager class into the partagers table.
 */
class PartagerDao extends AbstractPartagerDao
{
    /**
     * @return Partager[]|ResultIterator
     *
     * @throws StringsException
     *
     * @Query()
     * @Logged()
     */
    public function filterBySimulation(?string $simulationId): ResultIterator
    {
        return $this->findFromSql(
            'partagers',
            'partagers.simulation_id LIKE :simulationId',
            [
                'simulationId' => $simulationId ? sprintf('%%%s%%', $simulationId) : null,
            ]
        );
    }

    /**
     * @return Partager[]|ResultIterator
     *
     * @throws StringsException
     *
     * @Query()
     * @Logged()
     */
    public function filterByEnite(?string $entiteId): ResultIterator
    {
        return $this->findFromSql(
            'partagers',
            'partagers.entite_id LIKE :entiteId OR partagers.owner LIKE :entiteId',
            [
                'entiteId' => $entiteId ? sprintf('%%%s%%', $entiteId) : null,
            ]
        );
    }

    /**
     * @return Partager[]|ResultIterator
     *
     * @throws StringsException
     *
     * @Query()
     * @Logged()
     */
    public function findReadOnlyPartager(?string $userId, ?string $simulationId): ResultIterator
    {
        return $this->findFromSql(
            'partagers',
            'partagers.utilisateur_id = :userId AND partagers.simulation_id = :simulationId AND partagers.partage_type = "Lecture Seule"',
            [
                'userId' => $userId,
                'simulationId' => $simulationId,
            ]
        );
    }
}
