<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPatrimoineFoyerPeriodiqueDao;
use App\Model\PatrimoineFoyer;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The PatrimoineFoyerPeriodiqueDao class will maintain the persistence of PatrimoineFoyerPeriodique class into the patrimoine_foyers_periodique table.
 */
class PatrimoineFoyerPeriodiqueDao extends AbstractPatrimoineFoyerPeriodiqueDao
{
    public function findByPatrimoineFoyer(PatrimoineFoyer $patrimoineFoyer): ?ResultIterator
    {
        $patrimoineFoyerId = $patrimoineFoyer->getId();

        return $this->find('patrimoine_foyers_id = :patrimoineFoyerId', ['patrimoineFoyerId' => $patrimoineFoyerId]);
    }
}
