<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPatrimoineFoyerDao;
use App\Model\PatrimoineFoyer;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The PatrimoineFoyerDao class will maintain the persistence of PatrimoineFoyer class into the patrimoine_foyers table.
 */
class PatrimoineFoyerDao extends AbstractPatrimoineFoyerDao
{
    /**
     * @return ResultIterator|PatrimoineFoyer[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|PatrimoineFoyer[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }

    /**
     * @return ResultIterator|PatrimoineFoyer[]
     */
    public function findOneByNGroupe(string $simulation, int $nGroupe): ResultIterator
    {
        return $this->find([
            'simulation_id' => $simulation,
            'n_groupe' => $nGroupe,
        ]);
    }
}
