<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPatrimoineDao;
use App\Model\Patrimoine;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The PatrimoineDao class will maintain the persistence of Patrimoine class into the patrimoine table.
 */
class PatrimoineDao extends AbstractPatrimoineDao
{
    /**
     * @return ResultIterator|Patrimoine[]
     */
    public function findOneByNGroupe(string $simulation, int $nGroupe): ResultIterator
    {
        return $this->find([
            'simulation_id' => $simulation,
            'n_groupe' => $nGroupe,
        ]);
    }

    /**
     * @return ResultIterator|Patrimoine[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Patrimoine[]
     */
    public function findBySimulationIdAndNumeroGroupe(string $simulationId, int $numeroGroupe): ResultIterator
    {
        return $this->find([
            'simulation_id' => $simulationId,
            'n_groupe' =>  $numeroGroupe,
        ]);
    }

    /**
     * @return ResultIterator|Patrimoine[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }
}
