<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPatrimoineFoyerParametreDao;
use App\Model\PatrimoineFoyerParametre;

/**
 * The PatrimoineFoyerParametreDao class will maintain the persistence of PatrimoineFoyerParametre class into the patrimoine_foyers_parametres table.
 */
class PatrimoineFoyerParametreDao extends AbstractPatrimoineFoyerParametreDao
{
    public function findOneBySimulationId(string $simulationId): ?PatrimoineFoyerParametre
    {
        return $this->findOne('simulation_id = :simulationId', ['simulationId' => $simulationId]);
    }
}
