<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPatrimoineLogementParametreDao;
use App\Model\PatrimoineLogementParametre;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The PatrimoineLogementParametreDao class will maintain the persistence of PatrimoineLogementParametre class into the patrimoines_logements_parametres table.
 */
class PatrimoineLogementParametreDao extends AbstractPatrimoineLogementParametreDao
{
    /**
     * @return ResultIterator|PatrimoineLogementParametre[]
     */
    public function findBySimulationId(string $simulationId): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationId]);
    }

    public function findOneBySimulationId(string $simulationId): ?PatrimoineLogementParametre
    {
        return $this->findOne('simulation_id = :simulationId', ['simulationId' => $simulationId]);
    }
}
