<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPortageTresoreriePeriodiqueDao;
use App\Model\PortageTresoreriePeriodique;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\TDBMException;
use function Safe\sprintf;

/**
 * The PortageTresoreriePeriodiqueDao class will maintain the persistence of PortageTresoreriePeriodique class into the portage_tresorerie_periodique table.
 */
class PortageTresoreriePeriodiqueDao extends AbstractPortageTresoreriePeriodiqueDao
{
    /**
     * @throws TDBMException
     * @throws StringsException
     */
    public function findOneByPortageTresorerieIDAndIterartion(string $portageTresorerieID, int $iteration): PortageTresoreriePeriodique
    {
        $portageTresoreriePeriodique= $this->findOne([
            'portage_tresorerie_id' => $portageTresorerieID,
            'iteration' => $iteration,
        ]);
        if ($portageTresoreriePeriodique === null) {
            throw new TDBMException(sprintf('No row found for portage_tresorerie_id = %s and iteration = %d', $portageTresorerieID, $iteration));
        }

        return $portageTresoreriePeriodique;
    }
}
