<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPortageTresorerieParametreDao;
use App\Model\PortageTresorerieParametre;

/**
 * The PortageTresorerieParametreDao class will maintain the persistence of PortageTresorerieParametre class into the portage_tresorerie_parametre table.
 */
class PortageTresorerieParametreDao extends AbstractPortageTresorerieParametreDao
{
    public function findOneBySimulationId(string $simulationId): ?PortageTresorerieParametre
    {
        return $this->findOne('simulation_id = :simulationId', ['simulationId' => $simulationId]);
    }
}
