<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPortageTresorerieDao;
use App\Model\PortageTresorerie;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The PortageTresorerieDao class will maintain the persistence of PortageTresorerie class into the portage_tresorerie table.
 */
class PortageTresorerieDao extends AbstractPortageTresorerieDao
{
    /**
     * Get a PortageTresorerie filtered by simulationId.
     *
     * @return ResultIterator|PortageTresorerie[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|PortageTresorerie[]
     */
    public function findBySimulationAndType(string $simulationID, string $type): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'type' => $type,
        ];

        return $this->find($filter);
    }

    public function findOneBySimulationAndNom(Simulation $simulation, string $nom): ?PortageTresorerie
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
            'nom' => $nom,
        ];

        return $this->findOne($filter);
    }
}
