<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractProduitAutrePeriodiqueDao;
use App\Model\ProduitAutrePeriodique;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\TDBMException;
use function Safe\sprintf;

/**
 * The ProduitAutrePeriodiqueDao class will maintain the persistence of ProduitAutrePeriodique class into the produits_autres_periodique table.
 */
class ProduitAutrePeriodiqueDao extends AbstractProduitAutrePeriodiqueDao
{
    /**
     * @throws TDBMException
     * @throws StringsException
     */
    public function findOneByProduitAutreIDAndIterartion(string $produitAutreID, int $iteration): ProduitAutrePeriodique
    {
        $produitAutrePeriodique= $this->findOne([
            'produits_autres_id' => $produitAutreID,
            'iteration' => $iteration,
        ]);
        if ($produitAutrePeriodique === null) {
            throw new TDBMException(sprintf('No row found for produit_Autre_id = %s and iteration = %d', $produitAutreID, $iteration));
        }

        return $produitAutrePeriodique;
    }
}
