<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractProduitChargeDao;
use App\Model\ProduitCharge;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The ProduitChargeDao class will maintain the persistence of ProduitCharge class into the produits_charges table.
 */
class ProduitChargeDao extends AbstractProduitChargeDao
{
    /**
     * @return ResultIterator|ProduitCharge[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }

    public function findOneBySimulationIDAndLibelle(string $simulationID, string $libelle): ?ProduitCharge
    {
        return $this->findOne([
            'simulation_id' => $simulationID,
            'libelle' => $libelle,
        ]);
    }
}
