<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractProduitAutreDao;
use App\Model\ProduitAutre;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The ProduitAutreDao class will maintain the persistence of ProduitAutre class into the produits_autres table.
 */
class ProduitAutreDao extends AbstractProduitAutreDao
{
    /**
     * @return ResultIterator|ProduitAutre[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }

    /**
     * @return ResultIterator|ProduitAutre[]
     */
    public function findBySimulationIDAndType(string $simulationID, int $type): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'type' => $type,
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|ProduitAutre[]
     */
    public function findBySimulatonIdTypeNatureAndNom(string $simulationID, int $type, int $nature, string $nom): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'type' => $type,
            'nature' => $nature,
            'nom' => $nom,
        ];

        return $this->find($filter);
    }
}
