<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractProduitChargePeriodiqueDao;

/**
 * The ProduitChargePeriodiqueDao class will maintain the persistence of ProduitChargePeriodique class into the produits_charges_periodique table.
 */
class ProduitChargePeriodiqueDao extends AbstractProduitChargePeriodiqueDao
{
}
