<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractProfilEvolutionLoyerDao;
use App\Model\ProfilEvolutionLoyer;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The ProfilEvolutionLoyerDao class will maintain the persistence of ProfilEvolutionLoyer class into the profil_evolution_loyer table.
 */
class ProfilEvolutionLoyerDao extends AbstractProfilEvolutionLoyerDao
{
    /**
     * Get a ProfilEvolutionLoyer filtered by simulationId.
     *
     * @return ResultIterator|ProfilEvolutionLoyer[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|ProfilEvolutionLoyer[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }

    /**
     * @return ResultIterator|ProfilEvolutionLoyer[]
     */
    public function findByNumero(string $numero): ResultIterator
    {
        return $this->find(['numero' => $numero]);
    }

     /**
      * @return ResultIterator|ProfilEvolutionLoyer[]
      */
    public function fetchBySimulationIdAndNumero(string $simulationID, string $numero): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID, 'numero' => $numero]);
    }
}
