<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractProfilEvolutionLoyerParametreDao;
use App\Model\ProfilEvolutionLoyerParametre;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The ProfilEvolutionLoyerParametreDao class will maintain the persistence of ProfilEvolutionLoyerParametre class into the profils_evolution_loyers_parametre table.
 */
class ProfilEvolutionLoyerParametreDao extends AbstractProfilEvolutionLoyerParametreDao
{
    /**
     * @return ResultIterator|ProfilEvolutionLoyerParametre[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        $filter = ['simulation_id' => $simulationID];

        return $this->find($filter);
    }
}
