<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractProfilEvolutionLoyerPeriodiqueDao;
use App\Model\ProfilEvolutionLoyerPeriodique;

/**
 * The ProfilEvolutionLoyerPeriodiqueDao class will maintain the persistence of ProfilEvolutionLoyerPeriodique class into the profil_evolution_loyer_periodique table.
 */
class ProfilEvolutionLoyerPeriodiqueDao extends AbstractProfilEvolutionLoyerPeriodiqueDao
{
    public function findOneByIDAndIteration(string $profilId, int $iteration): ?ProfilEvolutionLoyerPeriodique
    {
        return $this->findOne([
            'profil_evolution_loyer_id' => $profilId,
            'iteration' => $iteration,
        ]);
    }
}
