<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPslaDao;
use App\Model\Psla;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The PslaDao class will maintain the persistence of Psla class into the psla table.
 */
class PslaDao extends AbstractPslaDao
{
    /**
     * @return ResultIterator|Psla[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Psla[]
     */
    public function findBySimulationIDAndType(string $simulationID, int $type): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'type' => $type,
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Psla[]
     */
    public function findOneByNumero(string $simulation, int $numero, int $type): ResultIterator
    {
        return $this->find([
            'simulation_id' => $simulation,
            'numero' => $numero,
            'type' => $type,
        ]);
    }
}
