<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPslaPeriodiqueDao;

/**
 * The PslaPeriodiqueDao class will maintain the persistence of PslaPeriodique class into the psla_periodique table.
 */
class PslaPeriodiqueDao extends AbstractPslaPeriodiqueDao
{
}
