<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractResultatComptableDao;
use App\Model\ResultatComptable;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The ResultatComptableDao class will maintain the persistence of ResultatComptable class into the resultat_comptable table.
 */
class ResultatComptableDao extends AbstractResultatComptableDao
{
    /**
     * @return ResultIterator|ResultatComptable[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }

    public function findOneBySimulationIDAndLibelle(string $simulationID, string $libelle): ?ResultatComptable
    {
        return $this->findOne([
            'simulation_id' => $simulationID,
            'libelle' => $libelle,
        ]);
    }

    /**
     * @return ResultIterator| ResultatComptable[]
     */
    public function findByLibelle(string $libelle): ResultIterator
    {
        return $this->find(['libelle' => $libelle]);
    }
}
