<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractResultatComptablePeriodiqueDao;

/**
 * The ResultatComptablePeriodiqueDao class will maintain the persistence of ResultatComptablePeriodique class into the resultat_comptable_periodique table.
 */
class ResultatComptablePeriodiqueDao extends AbstractResultatComptablePeriodiqueDao
{
}
