<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractRisqueLocatifDao;
use App\Model\RisqueLocatif;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The RisqueLocatifDao class will maintain the persistence of RisqueLocatif class into the risques_locatifs table.
 */
class RisqueLocatifDao extends AbstractRisqueLocatifDao
{
    /**
     * Get a RisqueLocatif filtered by simulationId.
     *
     * @return ResultIterator|RisqueLocatif[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|RisqueLocatif[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }
}
