<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractRoleDao;
use App\Model\Role;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\ResultIterator;
use function Safe\sprintf;

/**
 * The RoleDao class will maintain the persistence of Role class into the roles table.
 */
class RoleDao extends AbstractRoleDao
{
    /**
     * Get all Role records (exept admin)
     *
     * @return Role[]|ResultIterator
     *
     * @throws StringsException
     */
    public function getAll(): ResultIterator
    {
        $sortColumn = 'nom';
        $sortOrder = 'ASC';
        $filter = 'est_visible = true';

        return $this->find($filter, [], sprintf('%s %s', $sortColumn, $sortOrder));
    }

    /**
     * @param string[] $droits
     *
     * @return Role[]|ResultIterator
     *
     * @throws StringsException
     */
    public function findByFilters(
        ?string $nom,
        ?string $description,
        ?array $droits,
        string $sortColumn,
        string $sortOrder
    ): ResultIterator {
        // We need to specify this in order to prevent ambiguous error type because 'nom' is a field of multiple tables bellow
        if ($sortColumn === 'nom') {
            $sortColumn = 'roles.nom';
        }

        return $this->findFromSql(
            'roles
            LEFT JOIN roles_droits ON roles.id = roles_droits.role_id
            LEFT JOIN droits ON roles_droits.droit_id = droits.id',
            'roles.nom LIKE :nom
            AND roles.description LIKE :description
            AND droits.id in (:droits)',
            [
                'nom' => $nom ? sprintf('%%%s%%', $nom) : null,
                'description' => $description ? sprintf('%%%s%%', $description) : null,
                'droits' => $droits ? $droits : null,
            ],
            sprintf('%s %s', $sortColumn, $sortOrder)
        );
    }
}
