<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractSessionDao;

/**
 * The SessionDao class will maintain the persistence of Session class into the sessions table.
 */
class SessionDao extends AbstractSessionDao
{
}
