<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractSimulationNoteDao;
use App\Model\Simulation;
use App\Model\SimulationNote;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The SimulationNoteDao class will maintain the persistence of SimulationNote class into the simulations_notes table.
 */
class SimulationNoteDao extends AbstractSimulationNoteDao
{
    /**
     * @return SimulationNote[]|ResultIterator
     */
    public function getBySimulation(Simulation $simulation): ResultIterator
    {
        return $this->find('simulation_id = :simulationId', ['simulationId' => $simulation->getId()], 'date_creation ASC');
    }
}
