<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractSimulationDao;
use App\Model\Simulation;
use TheCodingMachine\TDBM\ResultIterator;
use function Safe\sprintf;

/**
 * The SimulationDao class will maintain the persistence of Simulation class into the simulations table.
 */
class SimulationDao extends AbstractSimulationDao
{
    /**
     * @return Simulation[]|ResultIterator
     */
    public function findByFilters(?string $anneeDeReference, ?string $nom, ?string $entiteId, ?string $ensembleId, ?string $entiteType, ?string $code): ResultIterator
    {
        return $this->findFromSql(
            'simulations
            LEFT JOIN entites ON simulations.entite = entites.id
            LEFT JOIN ensembles_entites ON entites.id = ensembles_entites.entite_id',
            'simulations.annee_de_reference = :anneeDeReference
            AND simulations.nom LIKE :nom
            AND entites.id = :entiteId
            AND ensembles_entites.ensemble_id = :ensembleId
            AND entites.type = :entiteType
            AND entites.code LIKE :code',
            [
                'anneeDeReference' => $anneeDeReference,
                'nom' => $nom ? sprintf('%%%s%%', $nom) : null,
                'entiteId'  => $entiteId,
                'ensembleId'  => $ensembleId,
                'entiteType'  => $entiteType,
                'code'  => $code ? sprintf('%%%s%%', $code) : null,
            ]
        );
    }

    /**
     * @return Simulation[]|ResultIterator
     */
    public function filterSimulationByShare(string $utilisateurId, ?string $entiteId, ?string $anneeDeReference, ?string $nom, ?string $ensembleId, ?string $entiteType, ?string $code): ResultIterator
    {
        return $this->findFromSql(
            'simulations
            LEFT JOIN entites ON simulations.entite = entites.id
            LEFT JOIN ensembles_entites ON entites.id = ensembles_entites.entite_id
            LEFT JOIN utilisateurs_roles_entites ON entites.id = utilisateurs_roles_entites.entite_id
            LEFT JOIN utilisateurs ON utilisateurs_roles_entites.utilisateur_id = entites.id
            LEFT JOIN partagers ON simulations.id = partagers.simulation_id',
            'entites.id = :entiteId
            AND simulations.supprime = :supprime
            AND (simulations.verrouille_par = :utilisateurId OR simulations.verrouille_par IS NULL)
            OR partagers.utilisateur_id = :utilisateurId
            AND simulations.annee_de_reference = :anneeDeReference
            AND simulations.nom LIKE :nom
            AND ensembles_entites.ensemble_id = :ensembleId
            AND entites.type = :entiteType
            AND entites.code LIKE :code',
            [
                'entiteId'  => $entiteId? $entiteId:null,
                'utilisateurId' => $utilisateurId,
                'anneeDeReference' => $anneeDeReference,
                'nom' => $nom ? sprintf('%%%s%%', $nom) : null,
                'ensembleId'  => $ensembleId,
                'entiteType'  => $entiteType,
                'code'  => $code ? sprintf('%%%s%%', $code) : null,
                'supprime' => false,
            ]
        );
    }
}
