<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractSimulationHistoriqueDao;
use App\Model\Simulation;
use App\Model\SimulationHistorique;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The SimulationHistoriqueDao class will maintain the persistence of SimulationHistorique class into the simulation_historiques table.
 */
class SimulationHistoriqueDao extends AbstractSimulationHistoriqueDao
{
    /**
     * @return SimulationHistorique[]|ResultIterator
     */
    public function getBySimulation(Simulation $simulation): ResultIterator
    {
        return $this->find('simulation_id = :simulationId', ['simulationId' => $simulation->getId()], 'date_creation ASC');
    }
}
