<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTableauDeBordPeriodiqueDao;
use App\Model\TableauDeBordPeriodique;

/**
 * The TableauDeBordPeriodiqueDao class will maintain the persistence of TableauDeBordPeriodique class into the tableau_de_bord_periodique table.
 */
class TableauDeBordPeriodiqueDao extends AbstractTableauDeBordPeriodiqueDao
{
    public function findByTableauParamIteration(string $tableautDeBordUUID, string $paramUUID, string $iteration): ?TableauDeBordPeriodique
    {
        $filter = [
            'tableau_de_bord_id' => $tableautDeBordUUID,
            'tableau_de_bord_param_id' => $paramUUID,
            'iteration' => $iteration,
        ];

        return $this->findOne($filter);
    }
}
