<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTableauDeBordParametreDao;
use App\Model\TableauDeBord;
use App\Model\TableauDeBordParametre;

/**
 * The TableauDeBordParametreDao class will maintain the persistence of TableauDeBordParametre class into the tableau_de_bord_parametre table.
 */
class TableauDeBordParametreDao extends AbstractTableauDeBordParametreDao
{
    public function findByComposantAndTableau(string $composant, TableauDeBord $tableauDeBord): ?TableauDeBordParametre
    {
        $filter = [
            'composant' => $composant,
            'tableau_de_bord_id' => $tableauDeBord->getUuid(),
        ];

        return $this->findOne($filter);
    }
}
