<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTableauDeBordDao;
use App\Model\TableauDeBord;

/**
 * The TableauDeBordDao class will maintain the persistence of TableauDeBord class into the tableau_de_bord table.
 */
class TableauDeBordDao extends AbstractTableauDeBordDao
{
    public function findBySimulationID(string $simulationID): ?TableauDeBord
    {
        return $this->findOne(['simulation_id' => $simulationID]);
    }
}
