<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTravauxFoyerDao;
use App\Model\TravauxFoyer;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The TravauxFoyerDao class will maintain the persistence of TravauxFoyer class into the travaux_foyer table.
 */
class TravauxFoyerDao extends AbstractTravauxFoyerDao
{
    /**
     * @return ResultIterator|TravauxFoyer[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }
}
