<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTravauxImmobiliseDao;
use App\Model\Simulation;
use App\Model\TravauxImmobilise;
use TheCodingMachine\TDBM\ResultIterator;
use function Safe\sprintf;

/**
 * The TravauxImmobiliseDao class will maintain the persistence of TravauxImmobilise class into the travaux_immobilises table.
 */
class TravauxImmobiliseDao extends AbstractTravauxImmobiliseDao
{
    /**
     * @return ResultIterator|TravauxImmobilise[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter, [], sprintf('%s %s', 'n_groupe', 'ASC'));
    }

    /**
     * @return ResultIterator|TravauxImmobilise[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        $filter = ['simulation_id' => $simulationID];

        return $this->find($filter, [], sprintf('%s %s', 'n_groupe', 'ASC'));
    }

    /**
     * @return ResultIterator|TravauxImmobilise[]
     */
    public function findBySimulationIDAndType(string $simulationID, int $type): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulationID,
            'type' => $type,
        ];

        return $this->find($filter, [], sprintf('%s %s', 'n_groupe', 'ASC'));
    }

    /**
     * @return ResultIterator|TravauxImmobilise[]
     */
    public function findOneByNGroupe(string $simulation, int $nGroupe, int $type): ResultIterator
    {
        return $this->find([
            'simulation_id' => $simulation,
            'n_groupe' => $nGroupe,
            'type' => $type,
        ]);
    }
}
