<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTravauxImmobilisePeriodiqueDao;

/**
 * The TravauxImmobilisePeriodiqueDao class will maintain the persistence of TravauxImmobilisePeriodique class into the travaux_immobilises_periodique table.
 */
class TravauxImmobilisePeriodiqueDao extends AbstractTravauxImmobilisePeriodiqueDao
{
}
