<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTravauxFoyerPeriodiqueDao;

/**
 * The TravauxFoyerPeriodiqueDao class will maintain the persistence of TravauxFoyerPeriodique class into the travaux_foyer_periodique table.
 */
class TravauxFoyerPeriodiqueDao extends AbstractTravauxFoyerPeriodiqueDao
{
}
