<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTypeEmpruntDemolitionFoyerDao;
use App\Model\TypeEmpruntDemolitionFoyer;

/**
 * The TypeEmpruntDemolitionFoyerDao class will maintain the persistence of TypeEmpruntDemolitionFoyer class into the type_emprunt_demolition_foyers table.
 */
class TypeEmpruntDemolitionFoyerDao extends AbstractTypeEmpruntDemolitionFoyerDao
{
    public function findByTypeEmpruntAndDemolitionFoyer(string $typesEmpruntsUUID, string $demolitionFoyerUUID): ?TypeEmpruntDemolitionFoyer
    {
        $filter = [
            'types_emprunts_id' => $typesEmpruntsUUID,
            'demolition_foyers_id' => $demolitionFoyerUUID,
        ];

        return $this->findOne($filter);
    }
}
