<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTypeEmpruntPslaDao;
use App\Model\TypeEmpruntPsla;

/**
 * The TypeEmpruntPslaDao class will maintain the persistence of TypeEmpruntPsla class into the type_emprunt_psla table.
 */
class TypeEmpruntPslaDao extends AbstractTypeEmpruntPslaDao
{
    public function findByTypeEmpruntAndPsla(string $typesEmpruntsUUID, string $operationUUID): ?TypeEmpruntPsla
    {
        $filter = [
            'types_emprunts_id' => $typesEmpruntsUUID,
            'psla_id' => $operationUUID,
        ];

        return $this->findOne($filter);
    }
}
