<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTypeEmpruntTravauxImmobiliseDao;
use App\Model\TypeEmpruntTravauxImmobilise;

/**
 * The TypeEmpruntTravauxImmobiliseDao class will maintain the persistence of TypeEmpruntTravauxImmobilise class into the type_emprunt_travaux_immobilises table.
 */
class TypeEmpruntTravauxImmobiliseDao extends AbstractTypeEmpruntTravauxImmobiliseDao
{
    public function findByTypeEmpruntAndTravauxImmobilise(string $typesEmpruntsUUID, string $travauxImmobiliseUUID): ?TypeEmpruntTravauxImmobilise
    {
        $filter = [
            'types_emprunts_id' => $typesEmpruntsUUID,
            'travaux_immobilises_id' => $travauxImmobiliseUUID,
        ];

        return $this->findOne($filter);
    }
}
