<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTypeEmpruntDemolitionDao;
use App\Model\TypeEmpruntDemolition;

/**
 * The TypeEmpruntDemolitionDao class will maintain the persistence of TypeEmpruntDemolition class into the type_emprunt_demolition table.
 */
class TypeEmpruntDemolitionDao extends AbstractTypeEmpruntDemolitionDao
{
    public function findByTypeEmpruntAndDemolition(string $typesEmpruntsUUID, string $demolitionUUID): ?TypeEmpruntDemolition
    {
        $filter = [
            'types_emprunts_id' => $typesEmpruntsUUID,
            'demolition_id' => $demolitionUUID,
        ];

        return $this->findOne($filter);
    }
}
