<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTypeEmpruntPeriodiqueDao;
use App\Model\TypeEmpruntPeriodique;
use Safe\Exceptions\StringsException;
use TheCodingMachine\TDBM\TDBMException;
use function Safe\sprintf;

/**
 * The TypeEmpruntPeriodiqueDao class will maintain the persistence of TypeEmpruntPeriodique class into the types_emprunts_periodique table.
 */
class TypeEmpruntPeriodiqueDao extends AbstractTypeEmpruntPeriodiqueDao
{
    /**
     * @throws TDBMException
     * @throws StringsException
     */
    public function findOneByIDAndIteration(string $id, int $iteration): TypeEmpruntPeriodique
    {
        $typeEmpruntPeriodique = $this->findOne([
            'types_emprunts_id' => $id,
            'iteration' => $iteration,
        ]);
        if ($typeEmpruntPeriodique === null) {
            throw new TDBMException(sprintf('No row found for types_emprunts_id = %s and iteration = %s', $id, $iteration));
        }

        return $typeEmpruntPeriodique;
    }
}
