<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTypeEmpruntDao;
use App\Model\TypeEmprunt;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The TypeEmpruntDao class will maintain the persistence of TypeEmprunt class into the types_emprunts table.
 */
class TypeEmpruntDao extends AbstractTypeEmpruntDao
{
    /**
     * @return ResultIterator|TypeEmprunt[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }

    /**
     * @return ResultIterator|TypeEmprunt[]
     */
    public function findByNumero(string $numero): ResultIterator
    {
        return $this->find(['numero' => $numero]);
    }
}
