<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTypeEmpruntTravauxFoyerDao;
use App\Model\TypeEmpruntTravauxFoyer;

/**
 * The TypeEmpruntTravauxFoyerDao class will maintain the persistence of TypeEmpruntTravauxFoyer class into the type_emprunt_travaux_foyer table.
 */
class TypeEmpruntTravauxFoyerDao extends AbstractTypeEmpruntTravauxFoyerDao
{
    public function findByTypeEmpruntAndTravauxFoyer(string $typesEmpruntsUUID, string $travauxFoyerUUID): ?TypeEmpruntTravauxFoyer
    {
        $filter = [
            'types_emprunts_id' => $typesEmpruntsUUID,
            'travaux_foyer_id' => $travauxFoyerUUID,
        ];

        return $this->findOne($filter);
    }
}
