<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTypeEmpruntNouveauxFoyerDao;
use App\Model\TypeEmpruntNouveauxFoyer;

/**
 * The TypeEmpruntNouveauxFoyerDao class will maintain the persistence of TypeEmpruntNouveauxFoyer class into the type_emprunt_nouveaux_foyer table.
 */
class TypeEmpruntNouveauxFoyerDao extends AbstractTypeEmpruntNouveauxFoyerDao
{
    public function findByTypeEmpruntAndNouveauxFoyer(string $typesEmpruntsUUID, string $nouveauxFoyerUUID): ?TypeEmpruntNouveauxFoyer
    {
        $filter = [
            'types_emprunts_id' => $typesEmpruntsUUID,
            'nouveaux_foyer_id' => $nouveauxFoyerUUID,
        ];

        return $this->findOne($filter);
    }
}
