<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTypeEmpruntOperationDao;
use App\Model\TypeEmpruntOperation;

/**
 * The TypeEmpruntOperationDao class will maintain the persistence of TypeEmpruntOperation class into the type_emprunt_operation table.
 */
class TypeEmpruntOperationDao extends AbstractTypeEmpruntOperationDao
{
    public function findByTypeEmpruntAndOperation(string $typesEmpruntsUUID, string $operationUUID): ?TypeEmpruntOperation
    {
        $filter = [
            'types_emprunts_id' => $typesEmpruntsUUID,
            'operation_id' => $operationUUID,
        ];

        return $this->findOne($filter);
    }
}
