<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractUtilisateurRoleEntiteDao;
use App\Model\Utilisateur;
use App\Model\UtilisateurRoleEntite;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The UtilisateurRoleEntiteDao class will maintain the persistence of UtilisateurRoleEntite class into the utilisateurs_roles_entites table.
 */
class UtilisateurRoleEntiteDao extends AbstractUtilisateurRoleEntiteDao
{
    public function findOneByFilter(string $entiteID, string $utilisateurID, string $roleID): ?UtilisateurRoleEntite
    {
        $filter = [
            'entite_id' => $entiteID,
            'utilisateur_id' => $utilisateurID,
            'role_id' => $roleID,
        ];

        return $this->findOne($filter);
    }

    public function findByUser(Utilisateur $user): ResultIterator
    {
        return $this->find('utilisateur_id = :userId', ['userId' => $user->getId()]);
    }
}
