<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractVacanceDao;
use App\Model\Simulation;
use App\Model\Vacance;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The VacanceDao class will maintain the persistence of Vacance class into the vacance table.
 */
class VacanceDao extends AbstractVacanceDao
{
    /**
     * @return ResultIterator|Vacance[]
     */
    public function findBySimulationID(string $simulationID): ResultIterator
    {
        return $this->find(['simulation_id' => $simulationID]);
    }

    /**
     * Get a Vacance filtered by simulationId.
     *
     * @return ResultIterator|Vacance[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Vacance[]
     */
    public function findOneByNumeroGroupe(string $simulation, int $numeroGroupe): ResultIterator
    {
        return $this->find([
            'simulation_id' => $simulation,
            'numero_groupe' => $numeroGroupe,
        ]);
    }
}
