<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractVacancePeriodiqueDao;
use App\Model\VacancePeriodique;

/**
 * The VacancePeriodiqueDao class will maintain the persistence of VacancePeriodique class into the vacance_periodique table.
 */
class VacancePeriodiqueDao extends AbstractVacancePeriodiqueDao
{
    public function findOneByIDAndIteration(string $vacanceId, int $iteration): ?VacancePeriodique
    {
        return $this->findOne([
            'vacance_id' => $vacanceId,
            'iteration' => $iteration,
        ]);
    }
}
