<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractVefaDao;
use App\Model\Simulation;
use App\Model\Vefa;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The VefaDao class will maintain the persistence of Vefa class into the vefa table.
 */
class VefaDao extends AbstractVefaDao
{
    /**
     * Get a Vefa filtered by simulation.
     *
     * @return ResultIterator|Vefa[]
     */
    public function findBySimulation(Simulation $simulation): ResultIterator
    {
        $filter = [
            'simulation_id' => $simulation->getId(),
        ];

        return $this->find($filter);
    }

    /**
     * @return ResultIterator|Vefa[]
     */
    public function findBySimulationIdAndType(string $simulationId, string $type): ResultIterator
    {
        return $this->find('simulation_id = :simulationId AND type = :type', ['simulation' => $simulationId, 'type' => $type]);
    }
}
