<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractVefaPeriodiqueDao;

/**
 * The VefaPeriodiqueDao class will maintain the persistence of VefaPeriodique class into the vefa_periodique table.
 */
class VefaPeriodiqueDao extends AbstractVefaPeriodiqueDao
{
}
