<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractAccessionProduitCharge;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The AccessionProduitCharge class maps the 'accession_produits_charges' table in database.
 *
 * @Type
 */
class AccessionProduitCharge extends AbstractAccessionProduitCharge
{
    public const TYPE_PRODUIT = 0;
    public const TYPE_CHARGE = 1;

    public const TYPE_LIST = [
        'Produit'        => self::TYPE_PRODUIT,
        'Charge'      => self::TYPE_CHARGE,
    ];
}
