<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractAccessionCodification;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The AccessionCodification class maps the 'accession_codifications' table in database.
 *
 * @Type
 */
class AccessionCodification extends AbstractAccessionCodification
{
}
