<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractAnnuite;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Annuite class maps the 'annuite' table in database.
 *
 * @Type
 */
class Annuite extends AbstractAnnuite
{
    public const NATURE_REMBOURSEMENT = 0;
    public const NATURE_CHARGES = 1;

    public const TYPE_ANNUITE_EMPRUNTS = 0;
    public const TYPE_ACNE = 1;
    public const TYPE_ICNE = 2;
    public const TYPE_REMBOURSEMENT = 3;
    public const TYPE_CHARGES = 4;

    public const TYPE_LIST = [
        self::TYPE_ANNUITE_EMPRUNTS,
        self::TYPE_ACNE,
        self::TYPE_ICNE,
        self::TYPE_REMBOURSEMENT,
        self::TYPE_CHARGES,
    ];

    public const DEFAULT_CONFIG = [
        'Remboursement en capital des emprunts locatifs'     => self::NATURE_REMBOURSEMENT,
        "Charges d'intérêts des emprunts locatifs"           => self::NATURE_CHARGES,
        "Charges d'intérêts émissions obligataires"          => self::NATURE_CHARGES,
        'Résultats sur SWAP'                                 => self::NATURE_CHARGES,
        'Baux emphytéotiques'                                => self::NATURE_REMBOURSEMENT,
        'Réaménagement de la dette - impact capital'         => self::NATURE_REMBOURSEMENT,
        'Réaménagement de la dette - impact intérêt'         => self::NATURE_CHARGES,
        'Remboursement anticipé - impact capital'            => self::NATURE_REMBOURSEMENT,
        'Remboursement anticipé - impact intérêt'            => self::NATURE_CHARGES,
        'Intérêts de préfinancement'                         => self::NATURE_CHARGES,
    ];

    public const DEFAULT_CONFIG1 = [
        'ACNE du patrimoine de référence'                    => self::TYPE_ACNE,
        'ICNE du patrimoine de référence'                    => self::TYPE_ICNE,
        'Remboursement en capital des autres emprunts'       => self::TYPE_REMBOURSEMENT,
        'Charges d\'intérét des autres emprunts'             => self::TYPE_CHARGES,
    ];
}
