<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractAutreChargePeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The AutreChargePeriodique class maps the 'autres_charges_periodique' table in database.
 *
 * @Type
 */
class AutreChargePeriodique extends AbstractAutreChargePeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
