<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractAutreCharge;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The AutreCharge class maps the 'autres_charges' table in database.
 *
 * @Type
 */
class AutreCharge extends AbstractAutreCharge
{
    public const NATURE_LIST = [
        'Frais de personnel',
        'Frais de gestion',
        'Taxes foncières',
        'Charges courantes',
        'Charges exceptionnelles',
    ];
}
