<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractCcmiPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The CcmiPeriodique class maps the 'ccmi_periodique' table in database.
 *
 * @Type
 */
class CcmiPeriodique extends AbstractCcmiPeriodique
{
}
