<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractCessionFoyerPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The CessionFoyerPeriodique class maps the 'cessions_foyers_periodique' table in database.
 *
 * @Type
 */
class CessionFoyerPeriodique extends AbstractCessionFoyerPeriodique
{
}
