<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractCessionPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The CessionPeriodique class maps the 'cession_periodique' table in database.
 *
 * @Type
 */
class CessionPeriodique extends AbstractCessionPeriodique
{
}
