<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractCessionFoyer;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The CessionFoyer class maps the 'cessions_foyers' table in database.
 *
 * @Type
 */
class CessionFoyer extends AbstractCessionFoyer
{
}
