<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractCgllAncolParametre;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The CgllAncolParametre class maps the 'cglls_ancols_parametre' table in database.
 *
 * @Type
 */
class CgllAncolParametre extends AbstractCgllAncolParametre
{
}
