<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractCgllAncolPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The CgllAncolPeriodique class maps the 'cglls_ancols_periodique' table in database.
 *
 * @Type
 */
class CgllAncolPeriodique extends AbstractCgllAncolPeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
