<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractCgllAncol;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The CgllAncol class maps the 'cglls_ancols' table in database.
 *
 * @Type
 */
class CgllAncol extends AbstractCgllAncol
{
    public const  COTISATION_DE_BASE_CGLLS = 'Cotisation de base CGLLS';

    public const  TAUX_APPLICABLE_AUX_PRODUITS_LOCATIFS_HORS_SLS = 'Taux applicable aux produits locatifs hors SLS (en %)';

    public const  TAUX_APPLICABLE_AU_SLS = 'Taux applicable au SLS (en %)';

    public const  MONTANT_DE_LA_REDUCTION_POUR_CHAQUE_MISE_EN_SERVICE_DE_LOGEMENT_ET_FOYER = 'Montant de la réduction pour chaque mise en service de logement et foyer (en €/logt)';

    public const  LOCATAIRES_BENEFICIAIRES_DE_APL = '% locataires bénéficiaires de l\'APL';

    public const  MONTANT_DE_LA_REDUCTION_PAR_BENEFICIAIRE_APL = 'Montant de la réduction par bénéficiaire de l\'APL (en €/logt)';

    public const  LOGEMENTS_ET_DE_FOYERS_EN_QPV = '% de logements et de foyers en QPV';

    public const  REDUCTION_POUR_LES_LOGEMENTS_EN_QPV = 'Montant de la réduction pour chaque logement et foyer en QPV (en €/logt et foyer)';

    public const  COTISATION_ADDITIONNELLE_CGLLS = 'Cotisation additionnelle CGLLS (en k€)';

    public const  TAUX_DE_RLS_MOYEN_POUR_LE_CALCUL_DU_LISSAGE = 'Taux de RLS moyen pour le calcul du lissage';

    public const  TAUX_DE_COTISATION_ANCOLS = 'Taux de cotisation ANCOLS (en %)';

    public const COEFFICIENT_DE_VARIATION_DE_LA_RLS = 'Coefficient de variation de la RLS (en %)';
}
