<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractCodification;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Codification class maps the 'codifications' table in database.
 *
 * @Type
 */
class Codification extends AbstractCodification
{
}
