<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractDemolitionFoyerPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The DemolitionFoyerPeriodique class maps the 'demolition_foyers_periodique' table in database.
 *
 * @Type
 */
class DemolitionFoyerPeriodique extends AbstractDemolitionFoyerPeriodique
{
}
