<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractDroit;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Droit class maps the 'droits' table in database.
 *
 * @Type
 */
class Droit extends AbstractDroit
{
}
