<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractEnsemble;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Ensemble class maps the 'ensembles' table in database.
 *
 * @Type
 */
class Ensemble extends AbstractEnsemble
{
}
