<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractEntite;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Entite class maps the 'entites' table in database.
 *
 * @Type
 */
class Entite extends AbstractEntite
{
    /*
     * Returns the list of Entites associated to this bean via the utilisateurs_roles_entites pivot
     * table.
     *
     * @GraphqlField

    public function getEntites() : array
    {
        return $this->_getRelationships('utilisateurs_roles_entites');
    }
*/
}
