<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractFondDeRoulement;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The FondDeRoulement class maps the 'fond_de_roulement' table in database.
 *
 * @Type
 */
class FondDeRoulement extends AbstractFondDeRoulement
{
    /* -------------------------------------- NOM ---------------------------------------------*/
    public const FONDS_PROPRES_SUR_IMMOBILISATION_DE_STRUCTURE = 'Fonds propres sur immobilisationS de structure';

    public const VARIATION_DU_CAPITAL_OU_DOTATIONS = 'Variation du capital';

    public const REMBOURSEMENT_ANTICIPES_NON_REFINANCIES = 'Remboursement anticipés non refinancés';

    public const PRIX_DE_CESSION_ACTIF_HORS_PATRIMOINE = 'Prix de cession d\'actifS hors patrimoine';

    public const PROVISION_POUR_GROS_ENTRETIEN = 'Provisions pour Gros entretien';

    public const PROVISIONS_POUR_RISQUES_SWAP = 'Provisions pour risques SWAP';

    public const PROVISIONS_POUR_INDEMNITES_DE_RETRAITE = 'Provisions pour indemnités de départ en retraite';

    public const DETTE_INTERETS_COMPOSATEURS = 'Dette d\'intérêts compensateurs';
    /* -------------------------------------- NOM ---------------------------------------------*/


    /* -------------------------------------- TYPE ---------------------------------------------*/
    public const AUTRES_VARIATIONS_POTENTIEL_FINANCIER = 'Autres variations potentiel financier';

    public const PROVISIONS_DE_HAUT_BILAN = 'Provisions de haut bilan';
    /* -------------------------------------- TYPE ---------------------------------------------*/
}
