<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractFondDeRoulementPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The FondDeRoulementPeriodique class maps the 'fond_de_roulement_periodique' table in database.
 *
 * @Type
 */
class FondDeRoulementPeriodique extends AbstractFondDeRoulementPeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
