<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractFondDeRoulementParametre;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The FondDeRoulementParametre class maps the 'fond_de_roulement_parametre' table in database.
 *
 * @Type
 */
class FondDeRoulementParametre extends AbstractFondDeRoulementParametre
{
}
