<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractFoyerFraiStructurePeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The FoyerFraiStructurePeriodique class maps the 'foyers_frais_structures_periodique' table in database.
 *
 * @Type
 */
class FoyerFraiStructurePeriodique extends AbstractFoyerFraiStructurePeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
