<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractFoyerFraiStructure;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The FoyerFraiStructure class maps the 'foyers_frais_structures' table in database.
 *
 * @Type
 */
class FoyerFraiStructure extends AbstractFoyerFraiStructure
{
    public const TYPE_FRAIS_PERSONNEL = 1;
    public const TYPE_FRAIS_GESTION = 0;

    public const TYPE_LIST = [
        'Frais de gestion'        => self::TYPE_FRAIS_GESTION,
        'Frais de personnel'      => self::TYPE_FRAIS_PERSONNEL,
    ];
}
