<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractFraiStructurePeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The FraiStructurePeriodique class maps the 'frais_structures_periodique' table in database.
 *
 * @Type
 */
class FraiStructurePeriodique extends AbstractFraiStructurePeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
