<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractHypothese;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Hypothese class maps the 'hypotheses' table in database.
 *
 * @Type
 */
class Hypothese extends AbstractHypothese
{
}
