<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractIndiceTaux;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The IndiceTaux class maps the 'indices_taux' table in database.
 *
 * @Type
 */
class IndiceTaux extends AbstractIndiceTaux
{
    public const TAUX_INFLATION_TYPE = "Taux d'inflation";

    public const TAUX_VARIATION_ICC_TYPE = "Taux de variation de l'ICC";

    public const TAUX_VARIATION_IRL_TYPE = "Taux de variation de l'IRL";

    public const TAUX_LIVRET_A_TYPE = 'Taux du livret A';

    public const TAUX_REMUNERATION_TRESORERIE_TYPE = 'Taux de rémunération de la trésorerie';

    public const TAUX_LIVRET_A_TYPE_SUB_TAUX_INFLATION_TYPE = 'Taux de livret A - Taux d\'inflation';

    public const TAUX_LIVRET_A_TYPE_SUB_TAUX_VARIATION_IRL_TYPE = 'Taux de livret A - Taux de variation de l\'IRL';

    public const TAUX_LIVRET_A_TYPE_SUB_TAUX_REMUNERATION_TRESORERIE_TYPE = 'Taux de livret A - Taux de rémunération de la trésorerie';
}
