<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractIndiceTauxPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The IndiceTauxPeriodique class maps the 'indices_taux_periodique' table in database.
 *
 * @Type
 */
class IndiceTauxPeriodique extends AbstractIndiceTauxPeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
