<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractInvitationEnsemble;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The InvitationEnsemble class maps the 'invitations_ensembles' table in database.
 *
 * @Type
 */
class InvitationEnsemble extends AbstractInvitationEnsemble
{
}
