<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractInvitationEntite;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The InvitationEntite class maps the 'invitations_entites' table in database.
 *
 * @Type
 */
class InvitationEntite extends AbstractInvitationEntite
{
}
