<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractLotissementPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The LotissementPeriodique class maps the 'lotissement_periodique' table in database.
 *
 * @Type
 */
class LotissementPeriodique extends AbstractLotissementPeriodique
{
}
