<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractLotissement;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Lotissement class maps the 'lotissement' table in database.
 *
 * @Type
 */
class Lotissement extends AbstractLotissement
{
    public const TYPE_IDENTIFIEE = 0;
    public const TYPE_NON_IDENTIFIEE = 1;

    public const TYPE_LIST = [
        self::TYPE_IDENTIFIEE,
        self::TYPE_NON_IDENTIFIEE,
    ];
}
