<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractLoyerPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The LoyerPeriodique class maps the 'loyer_periodique' table in database.
 *
 * @Type
 */
class LoyerPeriodique extends AbstractLoyerPeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
