<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractLoyer;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Loyer class maps the 'loyer' table in database.
 *
 * @Type
 */
class Loyer extends AbstractLoyer
{
    public const TYPE_LOGEMENTS = 0;
    public const TYPE_SOLIDARITE = 1;
    public const TYPE_AUTRES_LOYER = 2;

    public const TYPE_LIST = [
        self::TYPE_LOGEMENTS,
        self::TYPE_SOLIDARITE,
        self::TYPE_AUTRES_LOYER,
    ];

    public const DEFAULT_CONFIG = [
        'Paramètres' => self::TYPE_LOGEMENTS,
        'Taux de RLS sur le patrimoine de référence' => self::TYPE_SOLIDARITE,
        'Taux de RLS sur les opérations nouvelles'   => self::TYPE_SOLIDARITE,
        'Ajustement RLS en montant'                  => self::TYPE_SOLIDARITE,
        'Loyers théoriques des locaux commerciaux'   => self::TYPE_AUTRES_LOYER,
        'Loyers théoriques des garages parkings'     => self::TYPE_AUTRES_LOYER,
        'Produit du SLS'                             => self::TYPE_AUTRES_LOYER,
        'Produits des loyers à la relocation'        => self::TYPE_AUTRES_LOYER,
        'Autres produits'                            => self::TYPE_AUTRES_LOYER,
    ];
}
