<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractMaintenance;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Maintenance class maps the 'maintenance' table in database.
 *
 * @Type
 */
class Maintenance extends AbstractMaintenance
{
    public const NATURE_CONSOMMATION = 0;
    public const NATURE_FRAIS_PERSONNEL = 1;

    public const NATURE_LIST = [
        self::NATURE_CONSOMMATION,
        self::NATURE_FRAIS_PERSONNEL,
    ];

    public const TYPE_DETAIL_MAINTENACE = 0;
    public const TYPE_DETAIL_GROS_ENTRETIEN = 1;

    public const TYPE_LIST = [
        self::TYPE_DETAIL_MAINTENACE,
        self::TYPE_DETAIL_GROS_ENTRETIEN,
    ];

    public const DEFAULT_CONFIG = [
        'Maintenance courante' => [
            'regie' => false,
            'nature' => null,
            'type' => self::TYPE_DETAIL_MAINTENACE,
        ],
        'Maintenance courante en régie - consommation' => [
            'regie' => true,
            'nature' => self::NATURE_CONSOMMATION,
            'type' => self::TYPE_DETAIL_MAINTENACE,
        ],
        'Maintenance courante en régie - Frais de personnel' => [
            'regie' => false,
            'nature' => self::NATURE_FRAIS_PERSONNEL,
            'type' => self::TYPE_DETAIL_MAINTENACE,
        ],
        'Gros entretien' => [
            'regie' => false,
            'nature' => null,
            'type' => self::TYPE_DETAIL_GROS_ENTRETIEN,
        ],
        'Gros entretien en régie - consommations' => [
            'regie' => true,
            'nature' => self::NATURE_CONSOMMATION,
            'type' => self::TYPE_DETAIL_GROS_ENTRETIEN,
        ],
        'Gros entretien en régie - frais de personnel' => [
            'regie' => true,
            'nature' => self::NATURE_FRAIS_PERSONNEL,
            'type' => self::TYPE_DETAIL_GROS_ENTRETIEN,
        ],
    ];
}
