<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractModeleDamortissement;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ModeleDamortissement class maps the 'modele_damortissement' table in database.
 *
 * @Type
 */
class ModeleDamortissement extends AbstractModeleDamortissement
{
}
