<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractNotification;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Notification class maps the 'notifications' table in database.
 *
 * @Type
 */
class Notification extends AbstractNotification
{
}
