<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractNouveauxFoyer;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The NouveauxFoyer class maps the 'nouveaux_foyer' table in database.
 *
 * @Type
 */
class NouveauxFoyer extends AbstractNouveauxFoyer
{
}
