<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractPartager;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Partager class maps the 'partagers' table in database.
 *
 * @Type
 */
class Partager extends AbstractPartager
{
}
