<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractPatrimoine;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Patrimoine class maps the 'patrimoine' table in database.
 *
 * @Type
 */
class Patrimoine extends AbstractPatrimoine
{
}
