<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractPatrimoineLogementParametre;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The PatrimoineLogementParametre class maps the 'patrimoines_logements_parametres' table in database.
 *
 * @Type
 */
class PatrimoineLogementParametre extends AbstractPatrimoineLogementParametre
{
}
