<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractPatrimoineFoyerPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The PatrimoineFoyerPeriodique class maps the 'patrimoine_foyers_periodique' table in database.
 *
 * @Type
 */
class PatrimoineFoyerPeriodique extends AbstractPatrimoineFoyerPeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
