<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractPatrimoineFoyer;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The PatrimoineFoyer class maps the 'patrimoine_foyers' table in database.
 *
 * @Type
 */
class PatrimoineFoyer extends AbstractPatrimoineFoyer
{
}
