<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractPatrimoineFoyerParametre;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The PatrimoineFoyerParametre class maps the 'patrimoine_foyers_parametres' table in database.
 *
 * @Type
 */
class PatrimoineFoyerParametre extends AbstractPatrimoineFoyerParametre
{
}
