<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractPortageTresorerieParametre;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The PortageTresorerieParametre class maps the 'portage_tresorerie_parametre' table in database.
 *
 * @Type
 */
class PortageTresorerieParametre extends AbstractPortageTresorerieParametre
{
}
