<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractPortageTresoreriePeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The PortageTresoreriePeriodique class maps the 'portage_tresorerie_periodique' table in database.
 *
 * @Type
 */
class PortageTresoreriePeriodique extends AbstractPortageTresoreriePeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
