<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractPortageTresorerie;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The PortageTresorerie class maps the 'portage_tresorerie' table in database.
 *
 * @Type
 */
class PortageTresorerie extends AbstractPortageTresorerie
{
    public const PRELIMINAIRES_LOCATIFS = 'Préliminaires locatifs';

    public const RESERVES_FRONTIERES = 'Réserves foncières';

    public const FINANCEMENT_EXTERNE = 'Financement externe';

    public const TAUX_INTERET_DU_FINANCEMENT_EXTERNE = 'Taux d’intérêt du financement externe';

    public const PROMOTION_ACCESSION = 'Promotion Accession';

    public const SOLDE_EMPLOIS_RESSOURCES_OPERATION = 'Solde Emplois Ressources des opérations en cours à la fin ';

    public const SUBVENTIONS_A_ENCAISSER_SUR_OPERATIONS_LOCATIFS = 'Subventions à encaisser sur opérations locatives en cours et TNS à fin ';

    public const SOLDE_TVA_SUR_IMMOBILISATIONS_LOCATIVES = 'Solde de TVA sur immobilisations locatives';

    public const DETTES_DIVERSES_FOURNISSEURS_IMMOBILISATIONS = 'Dettes diverses fournisseurs d\'immobilisations';

    public const DETTES_CREANCES_EXPLOITATION = 'Dettes / Créances d’exploitation';

    public const DETTES_CREANCES_HORS_EXPLOITATION = 'Dettes / Créances hors d’exploitation';

    public const CONCOURS_BANCAIRES_COURANTS = 'Concours bancaires courants';

    public const TAUX_INTERETS_SUR_CONCOURS_BANCAIRES_COURANTS = 'Taux d’intérêts sur concours bancaires courants';
}
