<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractProduitAutrePeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ProduitAutrePeriodique class maps the 'produits_autres_periodique' table in database.
 *
 * @Type
 */
class ProduitAutrePeriodique extends AbstractProduitAutrePeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
