<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractProduitCharge;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ProduitCharge class maps the 'produits_charges' table in database.
 *
 * @Type
 */
class ProduitCharge extends AbstractProduitCharge
{
    public const TYPE_PRODUIT = 0;
    public const TYPE_CHARGE = 1;

    public const TYPE_LIST = [
        'Produit'        => self::TYPE_PRODUIT,
        'Charge'      => self::TYPE_CHARGE,
    ];
}
