<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractProduitAutre;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ProduitAutre class maps the 'produits_autres' table in database.
 *
 * @Type
 */
class ProduitAutre extends AbstractProduitAutre
{
    public const NATURE_EXCEPTIONNEL = 0;
    public const NATURE_COURANT = 1;
    public const NATURE_ACTIVITES = 2;

    public const NATURE_LIST = [
        self::NATURE_EXCEPTIONNEL,
        self::NATURE_COURANT,
        self::NATURE_ACTIVITES,
    ];

    public const TYPE_PRODUCTION_IMMOBILISEE = 0;
    public const TYPE_PRODUITS_FINANCIERS = 1;
    public const TYPE_PRODUIT_EXCEPTIONNEL = 2;

    public const TYPE_LIST = [
        self::TYPE_PRODUCTION_IMMOBILISEE,
        self::TYPE_PRODUITS_FINANCIERS,
        self::TYPE_PRODUIT_EXCEPTIONNEL,
    ];
}
