<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractProduitChargePeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ProduitChargePeriodique class maps the 'produits_charges_periodique' table in database.
 *
 * @Type
 */
class ProduitChargePeriodique extends AbstractProduitChargePeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
