<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractProfilEvolutionLoyerPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ProfilEvolutionLoyerPeriodique class maps the 'profil_evolution_loyer_periodique' table in database.
 *
 * @Type
 */
class ProfilEvolutionLoyerPeriodique extends AbstractProfilEvolutionLoyerPeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
