<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractProfilEvolutionLoyerParametre;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ProfilEvolutionLoyerParametre class maps the 'profils_evolution_loyers_parametre' table in database.
 *
 * @Type
 */
class ProfilEvolutionLoyerParametre extends AbstractProfilEvolutionLoyerParametre
{
}
