<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractProfilEvolutionLoyer;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ProfilEvolutionLoyer class maps the 'profil_evolution_loyer' table in database.
 *
 * @Type
 */
class ProfilEvolutionLoyer extends AbstractProfilEvolutionLoyer
{
}
