<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractPslaPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The PslaPeriodique class maps the 'psla_periodique' table in database.
 *
 * @Type
 */
class PslaPeriodique extends AbstractPslaPeriodique
{
}
