<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractResultatComptablePeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ResultatComptablePeriodique class maps the 'resultat_comptable_periodique' table in database.
 *
 * @Type
 */
class ResultatComptablePeriodique extends AbstractResultatComptablePeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
