<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractResultatComptable;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The ResultatComptable class maps the 'resultat_comptable' table in database.
 *
 * @Type
 */
class ResultatComptable extends AbstractResultatComptable
{
    public const DEFAULT_CONFIG = [
        'Dotations pour dépréciations sur immobilisations',
        'Reprises de provisions sur immobilisations',
        'Dotations pour dépréciations sur stocks',
        'Reprises de provisions sur stocks',
        'Dotations pour dépréciations sur créances',
        'Reprises de provisions sur créances',
        'Dotations aux amortissements techniques du patrimoine de référence locatif',
        'Reprises de subventions du patrimoine de référence',
        'Dotations aux amortissements des immobilisations de structure',
        'Dotations aux amortissements et dépréciations financiers',
        'Reprises aux amortissements et dépréciations financiers',
        'Autres dotations y compris exceptionnelles',
        'Autres reprises y compris exceptionnelles',
    ];
}
