<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractRisqueLocatif;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The RisqueLocatif class maps the 'risques_locatifs' table in database.
 *
 * @Type
 */
class RisqueLocatif extends AbstractRisqueLocatif
{
    public const ACNE = 0;
    public const TAUX_VACANCE_PATRIMOINE = 1;
    public const TAUX_VACANCE_GARAGES = 2;
    public const TAUX_VACANCE_COMMERCIAUX = 3;
    public const TAUX_ANNUEL = 4;

    public const TYPE_LIST = [
        self::ACNE,
        self::TAUX_VACANCE_PATRIMOINE,
        self::TAUX_VACANCE_GARAGES,
        self::TAUX_VACANCE_COMMERCIAUX,
        self::TAUX_ANNUEL,
    ];

    public const NUMBER_OF_ITERATIONS = 50;
}
