<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractRole;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Role class maps the 'roles' table in database.
 *
 * @Type
 */
class Role extends AbstractRole
{
}
