<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractSession;

/**
 * The Session class maps the 'sessions' table in database.
 */
class Session extends AbstractSession
{
}
