<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractSimulationHistorique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The SimulationHistorique class maps the 'simulation_historiques' table in database.
 *
 * @Type
 */
class SimulationHistorique extends AbstractSimulationHistorique
{
}
