<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractSimulationNote;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The SimulationNote class maps the 'simulations_notes' table in database.
 *
 * @Type
 */
class SimulationNote extends AbstractSimulationNote
{
}
