<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractSimulation;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Simulation class maps the 'simulations' table in database.
 *
 * @Type
 */
class Simulation extends AbstractSimulation
{
}
