<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTableauDeBordParametre;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TableauDeBordParametre class maps the 'tableau_de_bord_parametre' table in database.
 *
 * @Type
 */
class TableauDeBordParametre extends AbstractTableauDeBordParametre
{
}
