<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTableauDeBordPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TableauDeBordPeriodique class maps the 'tableau_de_bord_periodique' table in database.
 *
 * @Type
 */
class TableauDeBordPeriodique extends AbstractTableauDeBordPeriodique
{
    public const NUMBER_OF_ITERATIONS = 51;
}
