<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTableauDeBord;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TableauDeBord class maps the 'tableau_de_bord' table in database.
 *
 * @Type
 */
class TableauDeBord extends AbstractTableauDeBord
{
    public const COMPOSANT_LIST = [
        'Patrimoine' => [
            'iteration' => 'years',
            'type' => 'Line',
            'data' => [14571, 10777, 9043, 2512,4482,3148,3585,2273,880,753,658],
            'position' => 1,
        ],
        'Annuites' => [
            'iteration' => 'years',
            'type' => 'Line',
            'data' => [14571, 10777, 9043, 2512,4482,3148,3585,2273,880,753,658],
            'position' => 2,
        ],
        'Maintenance travaux' => [
            'iteration' => 'years',
            'type' => 'Line',
            'data' => [14571, 10777, 9043, 2512,4482,3148,3585,2273,880,753,658],
            'position' => 3,
        ],
        'Coût de fonctionnement locatif' => [
            'iteration' => 'years',
            'type' => 'Line',
            'data' => [14571, 10777, 9043, 2512,4482,3148,3585,2273,880,753,658],
            'position' => 4,
        ],
        'Autofinancement net' => [
            'iteration' => 'years',
            'type' => 'Bar',
            'data' => [14571, 10777, 9043, 2512,4482,3148,3585,2273,880,753,658],
            'position' => 5,
        ],
        'Potentiel financier' => [
            'iteration' => 'years',
            'type' => 'Bar',
            'data' => [14571, 10777, 9043, 2512,4482,3148,3585,2273,880,753,658],
            'position' => 6,
        ],
        'Fond de roulement Long Terme' => [
            'iteration' => 'years',
            'type' => 'Bar',
            'data' => [14571, 10777, 9043, 2512,4482,3148,3585,2273,880,753,658],
            'position' => 7,
        ],
        'Nature des investissements' => [
            'iteration' => ['Composants', 'Neufs', 'Réhabilitations', 'Démolitions'],
            'type' => 'Doughnut',
            'data' => [4, 78, 17, 1],
            'position' => 8,
        ],
        'Plan de financement' => [
            'iteration' => ['Emprunts', 'Subventions', 'Fonds propres'],
            'type' => 'Doughnut',
            'data' => [4, 78, 17],
            'position' => 9,
        ],
    ];
}
