<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTravauxFoyer;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TravauxFoyer class maps the 'travaux_foyer' table in database.
 *
 * @Type
 */
class TravauxFoyer extends AbstractTravauxFoyer
{
}
