<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTravauxImmobilise;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TravauxImmobilise class maps the 'travaux_immobilises' table in database.
 *
 * @Type
 */
class TravauxImmobilise extends AbstractTravauxImmobilise
{
    public const TYPE_RENOUVELLEMENT = 0;
    public const TYPE_IDENTIFIEE = 1;
    public const TYPE_NON_IDENTIFIEE = 2;

    public const TYPE_LIST = [
        self::TYPE_RENOUVELLEMENT,
        self::TYPE_IDENTIFIEE,
        self::TYPE_NON_IDENTIFIEE,
    ];
}
