<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTravauxFoyerPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TravauxFoyerPeriodique class maps the 'travaux_foyer_periodique' table in database.
 *
 * @Type
 */
class TravauxFoyerPeriodique extends AbstractTravauxFoyerPeriodique
{
}
