<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTravauxImmobilisePeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TravauxImmobilisePeriodique class maps the 'travaux_immobilises_periodique' table in database.
 *
 * @Type
 */
class TravauxImmobilisePeriodique extends AbstractTravauxImmobilisePeriodique
{
}
