<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTypeEmpruntTravauxFoyer;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TypeEmpruntTravauxFoyer class maps the 'type_emprunt_travaux_foyer' table in database.
 *
 * @Type
 */
class TypeEmpruntTravauxFoyer extends AbstractTypeEmpruntTravauxFoyer
{
}
