<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTypeEmpruntOperation;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TypeEmpruntOperation class maps the 'type_emprunt_operation' table in database.
 *
 * @Type
 */
class TypeEmpruntOperation extends AbstractTypeEmpruntOperation
{
}
