<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTypeEmpruntTravauxImmobilise;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TypeEmpruntTravauxImmobilise class maps the 'type_emprunt_travaux_immobilises' table in database.
 *
 * @Type
 */
class TypeEmpruntTravauxImmobilise extends AbstractTypeEmpruntTravauxImmobilise
{
}
