<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTypeEmpruntPsla;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TypeEmpruntPsla class maps the 'type_emprunt_psla' table in database.
 *
 * @Type
 */
class TypeEmpruntPsla extends AbstractTypeEmpruntPsla
{
}
