<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTypeEmpruntNouveauxFoyer;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TypeEmpruntNouveauxFoyer class maps the 'type_emprunt_nouveaux_foyer' table in database.
 *
 * @Type
 */
class TypeEmpruntNouveauxFoyer extends AbstractTypeEmpruntNouveauxFoyer
{
}
