<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTypeEmprunt;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TypeEmprunt class maps the 'types_emprunts' table in database.
 *
 * @Type
 */
class TypeEmprunt extends AbstractTypeEmprunt
{
    public const SIMPLE = 0;
    public const DOUBLE = 1;
    public const DOUBLE_LIMITE = 2;
}
