<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTypeEmpruntPeriodique;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TypeEmpruntPeriodique class maps the 'types_emprunts_periodique' table in database.
 *
 * @Type
 */
class TypeEmpruntPeriodique extends AbstractTypeEmpruntPeriodique
{
    public const NUMBER_OF_ITERATIONS = 50;
}
