<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTypeEmpruntDemolition;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The TypeEmpruntDemolition class maps the 'type_emprunt_demolition' table in database.
 *
 * @Type
 */
class TypeEmpruntDemolition extends AbstractTypeEmpruntDemolition
{
}
