<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractUtilisateur;
use Symfony\Component\Security\Core\User\UserInterface;
use TheCodingMachine\GraphQLite\Annotations\Type;
use function array_push;

/**
 * The Utilisateur class maps the 'utilisateurs' table in database.
 *
 * @Type
 */
class Utilisateur extends AbstractUtilisateur implements UserInterface
{
    /**
     * @return mixed[]
     */
    public function toSecurityMap(): array
    {
        $rolesPerEntites = $this->getUtilisateursRolesEntites();
        $droitsPerEntites = [];
        $roles = [];
        $isReferent = false;
        foreach ($rolesPerEntites as $roleEntite) {
            $droits = $roleEntite->getRole()->getDroits();
            foreach ($droits as $droit) {
                $droitsPerEntites[$roleEntite->getEntite()->getId()] = $droit->getLibelle();
            }
            if (empty($roles[$roleEntite->getEntite()->getId()])) {
                $roles[$roleEntite->getEntite()->getId()] = [$roleEntite->getRole()->getNom()];
            }
            array_push($roles[$roleEntite->getEntite()->getId()], $roleEntite->getRole()->getNom());
            if ($roleEntite->getRole()->getNom() !== 'Référent entité' && $roleEntite->getRole()->getNom() !== 'Référent ensemble') {
                continue;
            }

            $isReferent = true;
        }

        return [
            'id' => $this->getId(),
            'nom' => $this->getNom(),
            'prenom' => $this->getPrenom(),
            'email' => $this->getEmail(),
            'fonction' => $this->getFonction(),
            'telephone' => $this->getTelephone(),
            'estAdministrateurCentral' => $this->getEstAdministrateurCentral(),
            'estAdministrateurSimulation' => $this->getEstAdministrateurSimulation(),
            'droits' => $droitsPerEntites,
            'roles' => $roles,
            'isReferent' => $isReferent,
        ];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername(): string
    {
        return $this->getNom() . '' . $this->getPrenom();
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials(): void
    {
        parent::setMotDePasse('');
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles(): array
    {
        return $this->getUtilisateursRolesEntites()->toArray();
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string|null The encoded password if any
     */
    public function getPassword(): ?string
    {
        return $this->getMotDePasse();
    }
}
