<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractUtilisateurRoleEntite;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The UtilisateurRoleEntite class maps the 'utilisateurs_roles_entites' table in database.
 *
 * @Type
 */
class UtilisateurRoleEntite extends AbstractUtilisateurRoleEntite
{
}
