<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractVefa;
use TheCodingMachine\GraphQLite\Annotations\Type;

/**
 * The Vefa class maps the 'vefa' table in database.
 *
 * @Type
 */
class Vefa extends AbstractVefa
{
    public const TYPE_IDENTIFIEE = 'Identifiée';
    public const TYPE_NON_IDENTIFIEE = 'Non identifiée';
}
