mutation removeTypeDempruntDemolition($typesEmpruntsUUID: String!, $demolitionUUID: String!) {
  removeTypeDempruntDemolition(
    typesEmpruntsUUID: $typesEmpruntsUUID,
    demolitionUUID: $demolitionUUID
  )
}