mutation removeTypeDempruntNouveauxFoyer($typesEmpruntsUUID: String!, $nouveauxFoyerUUID: String!) {
  removeTypeDempruntNouveauxFoyer(
    typesEmpruntsUUID: $typesEmpruntsUUID,
    nouveauxFoyerUUID: $nouveauxFoyerUUID
  )
}