query operations($simulationId: String!, $total: Boolean = false){
  operations(simulationId: $simulationId) {
    items @skip(if: $total) {
      id,
      simulation{
        nom,
        description
      },
      profilLoyer{
        id,
        numero,
        nom
      },
      modeleDamortissement{
        id,
        numero,
        nom
      },
      nOperation,
      nom,
      natureOperation,
      conventionAnru,
      videOccupe,
      secteurFinancement,
      surfaceQuittancee,
      nombreLogements,
      loyerMensuel,
      indexeIrl,
      nombreGarages,
      loyerMensuelGarages,
      nombreCommerces,
      loyerMensuelCommerces,
      anneAgrement,
      dateOrdreService,
      dateMiseService,
      acquisitionFin,
      dureeTravaux,
      dureeChantier,
      tfpbLogt,
      tfpbDuree,
      indexationIcc,
      prixFoncier,
      prixRevient,
      fondsPropres,
      subventionsEtat,
      subventionsAnru,
      subventionsEpci,
      subventionsDepartement,
      subventionsRegion,
      subventionsCollecteur,
      subventionsAutres,
      total,
      resteFinancer,
      tfpbTauxEvolution,
      maintenanceTauxEvolution,
      grosTauxEvolution,
      moyenOperation,
      moyenFoncier,
      type,
      operationPeriodique{
        items{
          iteration,
          tauxEvolutionLoyer,
          complementLoyer,
          complementAnnuiteCapital,
          complementAnnuiteInteret,
          tauxVacance,
          tfpb,
          maintenanceCourante,
          grosEntretien,
          nombreAgrement,
          nombreLogement,
          loyerMensuel,
          nombreLots,
          depotGarantie,
          nbGarages
        }
      },
      typeEmpruntOperation{
        items{
          montant,
          datePremiere,
          typesEmprunts {
            id,
            nom
          }
        }
      }
    }
    count @include(if: $total)
  }
}