mutation removeTypeDempruntOperation($typesEmpruntsUUID: String!, $operationUUID: String!){
  removeTypeDempruntOperation(
    typesEmpruntsUUID: $typesEmpruntsUUID,
    operationUUID: $operationUUID
  )
}