mutation saveOperation($operation: OperationInput!) {
  saveOperation(operation:$operation) {
    id,
    simulation{
      nom,
      description
    },
    profilLoyer{
      numero,
      nom
    },
    modeleDamortissement{
      numero,
      nom
    },
    nOperation,
    nom,
    natureOperation,
    conventionAnru,
    videOccupe,
    secteurFinancement,
    surfaceQuittancee,
    nombreLogements,
    loyerMensuel,
    indexeIrl,
    nombreGarages,
    loyerMensuelGarages,
    nombreCommerces,
    loyerMensuelCommerces,
    anneAgrement,
    dateOrdreService,
    dateMiseService,
    acquisitionFin,
    dureeTravaux,
    tfpbLogt,
    tfpbDuree,
    indexationIcc,
    prixFoncier,
    prixRevient,
    fondsPropres,
    subventionsEtat,
    subventionsAnru,
    subventionsEpci,
    subventionsDepartement,
    subventionsRegion,
    subventionsCollecteur,
    subventionsAutres,
    total,
    resteFinancer,
    depotGarantie,
    tfpbTauxEvolution,
    maintenanceTauxEvolution,
    grosTauxEvolution,
    type,
    operationPeriodique{
      items{
        iteration,
        tauxEvolutionLoyer,
        complementLoyer,
        complementAnnuiteCapital,
        complementAnnuiteInteret,
        tauxVacance,
        tfpb,
        maintenanceCourante,
        grosEntretien,
        nombreAgrement,
        nombreLogement,
        loyerMensuel,
        nombreLots
      }
    },
    typeEmpruntOperation{
      items{
        montant,
        datePremiere
      }
    }
  }
}